mod prelude;

holon_macros::builder_registry!("src/shadow_builders",
    skip: [prelude],
    register: ViewModel,
    widget_metas
);

use crate::render_interpreter::{shared_col_build, RenderInterpreter};
use crate::view_model::ViewModel;

pub fn create_shadow_interpreter() -> RenderInterpreter<ViewModel> {
    let mut interp = RenderInterpreter::new();
    register_all(&mut interp);
    interp.register("col", |ba: prelude::BA<'_>| {
        let children: Vec<ViewModel> = shared_col_build(&ba);
        ViewModel::layout("col", children)
    });
    // No annotator — operations flow through ProfileResolver → render_block builder,
    // not through RenderExpr FunctionCall.operations → context → annotator.
    interp
}

// all_widget_metas() is auto-generated by builder_registry! above
