//! File-per-transition pattern for the E2E PBT.
//!
//! Each transition kind owns its data (a struct), generation strategy
//! (`E2ETransitionFactory`), and behaviour (`E2ETransitionImpl`). The
//! `declare_e2e_transitions!` macro generates the dispatch enum, the
//! trait impls on the enum, and the strategy aggregator.
//!
//! See `experiments/enum-dispatch-examples/pbt-state-machine/` for the
//! standalone proof-of-concept; this module ports that pattern into
//! the real PBT.
//!
//! ## Two traits
//!
//! - `E2ETransitionImpl` (generated by the macro) holds the per-
//!   transition behaviour: preconditions, ref-state apply, async SUT
//!   apply, expected SQL budget. Native `async fn` — the macro emits
//!   `match self { ... v.apply_to_sut(sut).await }` so no
//!   `#[async_trait]` is needed. Not object-safe; only used through
//!   the concrete enum.
//!
//! - `SutHandle` (this file) is the object-safe view a transition
//!   uses to drive the SUT. `#[async_trait]` so `&mut dyn SutHandle`
//!   works under generic-V SUTs. The trait grows methods as variants
//!   are migrated; today it is empty.

use proptest::strategy::BoxedStrategy;
use validated::Validated;

use super::reference_state::ReferenceState;
use super::validation::Reason;

/// Static contract for *creating* a transition. Sibling to
/// `E2ETransitionImpl` (which is generated by `declare_e2e_transitions!`
/// and holds the instance methods).
///
/// Lives outside the macro because static methods can't be enum-
/// dispatched — there's no `self` to match on. Each variant impls this
/// directly; the strategy aggregator calls it per-type.
pub trait E2ETransitionFactory: Sized {
    /// If this transition kind applies in `state`, return
    /// `Good((weight, generator))` for the proptest aggregator. On rejection,
    /// return `Fail(reasons)` — each named reason is recorded into the
    /// rejection histogram so the runner can surface *why* a transition was
    /// never generated. `Fail` removes the variant from this step entirely
    /// (no wasted strategy construction, no zero-weight bookkeeping).
    fn weighted_generator(state: &ReferenceState) -> Validated<(u32, BoxedStrategy<Self>), Reason>;
}

/// Per-variant weight multiplier read from the `HOLON_PBT_WEIGHTS`
/// environment variable. The macro `declare_e2e_transitions!` applies
/// this automatically to every arm of `aggregate_transitions`, so
/// individual variants don't need to wire it themselves.
///
/// Format: comma-separated `pattern:multiplier` pairs.
/// `pattern` is matched case-insensitively against the variant name.
/// Patterns may contain a single `*` glob for prefix / suffix /
/// contains matching.
///
/// Examples:
///
/// ```text
/// HOLON_PBT_WEIGHTS=Indent:200            # boost a single variant
/// HOLON_PBT_WEIGHTS=Indent:200,Outdent:200,ToggleState:200,Move*:100
/// HOLON_PBT_WEIGHTS=*Edit*:0,Click*:50    # silence one family, boost another
/// ```
///
/// Multiplier `0` removes the variant from the strategy entirely
/// (`weighted_generator` still computes its base weight, but
/// `Union::new_weighted` drops zero-weight arms). Multiplier defaults
/// to `1` for any variant not matched by any pattern.
///
/// Why a single env var: previously each "interesting family"
/// (chord ops, navigation, edit) needed its own bespoke env var
/// wired into each variant's `weighted_generator`. The macro-applied
/// generic shim lets future verification work tune any subset
/// without touching transition source.
pub fn variant_weight_multiplier(variant_name: &'static str) -> u32 {
    use std::sync::OnceLock;

    static PARSED: OnceLock<Vec<(WeightPattern, u32)>> = OnceLock::new();
    let rules = PARSED.get_or_init(parse_weight_env);
    if rules.is_empty() {
        return 1;
    }
    for (pattern, mult) in rules {
        if pattern.matches(variant_name) {
            return *mult;
        }
    }
    1
}

#[derive(Debug)]
enum WeightPattern {
    Exact(String),
    Prefix(String),
    Suffix(String),
    Contains(String),
    Star, // bare `*` → matches every variant
}

impl WeightPattern {
    fn matches(&self, name: &str) -> bool {
        let n = name.to_ascii_lowercase();
        match self {
            Self::Exact(s) => n == *s,
            Self::Prefix(s) => n.starts_with(s),
            Self::Suffix(s) => n.ends_with(s),
            Self::Contains(s) => n.contains(s),
            Self::Star => true,
        }
    }
}

fn parse_weight_env() -> Vec<(WeightPattern, u32)> {
    let raw = match std::env::var("HOLON_PBT_WEIGHTS") {
        Ok(s) if !s.is_empty() => s,
        _ => return Vec::new(),
    };
    let mut rules = Vec::new();
    for entry in raw.split(',') {
        let entry = entry.trim();
        if entry.is_empty() {
            continue;
        }
        let Some((pat_raw, mult_raw)) = entry.split_once(':') else {
            eprintln!("[HOLON_PBT_WEIGHTS] ignoring '{entry}': expected `pattern:multiplier`");
            continue;
        };
        let mult: u32 = match mult_raw.trim().parse() {
            Ok(n) => n,
            Err(_) => {
                eprintln!("[HOLON_PBT_WEIGHTS] ignoring '{entry}': multiplier must be a u32");
                continue;
            }
        };
        let pat_lower = pat_raw.trim().to_ascii_lowercase();
        let pattern = if pat_lower == "*" {
            WeightPattern::Star
        } else if let Some(stripped) = pat_lower.strip_prefix('*') {
            if let Some(middle) = stripped.strip_suffix('*') {
                WeightPattern::Contains(middle.to_string())
            } else {
                WeightPattern::Suffix(stripped.to_string())
            }
        } else if let Some(stripped) = pat_lower.strip_suffix('*') {
            WeightPattern::Prefix(stripped.to_string())
        } else {
            WeightPattern::Exact(pat_lower)
        };
        rules.push((pattern, mult));
    }
    rules
}

/// Object-safe handle into the real SUT. Hides the
/// `<V: VariantMarker>` type parameter so transitions can call SUT
/// methods through `&mut dyn SutHandle`.
///
/// `?Send` because `E2ESut<V>` holds `RefCell` fields (interior
/// mutability for the reactive engine) and can't be `Sync`. The
/// existing top-level `apply_transition_async` path is non-Send for
/// the same reason — proptest's state-machine driver runs on a single
/// thread via `runtime.block_on`, so Send isn't required.
///
/// Implemented for `E2ESut<V>` in `sut.rs`. The trait grows methods as
/// variants are migrated; each migration that needs a new SUT
/// capability adds one method here and one impl in `sut.rs`
/// (delegating to existing helpers).
#[async_trait::async_trait(?Send)]
pub trait SutHandle {
    /// Shared-PBT capability: synthesize a click on a UI element by
    /// its bounds-registry id. Used by `holon_layout_testing`'s shared
    /// `apply_to_sut` bodies (`SwitchViewMode`, `ToggleDrawer`,
    /// `ToggleCollapse`) via `SutClickAdapter`. Default impl panics
    /// loud — concrete SUTs override with their click pipeline (e.g.
    /// `GpuiUserDriver::click_entity`).
    async fn apply_click_at_element(&mut self, element_id: &str) {
        let _ = element_id;
        unimplemented!(
            "SutHandle::apply_click_at_element — the concrete SUT for this PBT \
             variant hasn't been migrated to support shared layout interactions yet."
        )
    }

    /// Shared-PBT capability: push deferred `live_block` content
    /// through the SUT's data-arrival pipeline. Mirror of the layout
    /// PBT's `LiveBlockSink::deliver_block_content_loaded`. Default
    /// panics — real backend tests should override or skip
    /// `DeliverBlockContent` from their generator.
    async fn apply_deliver_block_content_loaded(&mut self, block_id: &str) {
        let _ = block_id;
        unimplemented!(
            "SutHandle::apply_deliver_block_content_loaded — the integration-tests \
             PBT runs a real backend; deferred block delivery isn't a meaningful \
             stimulus there. Skip `DeliverBlockContent` in the generator."
        )
    }

    /// Pilot-variant capability: drive the navigation back-button via
    /// `TestContext::navigate_back` and dump nav tables for tracing.
    async fn navigate_back(&mut self, region: holon_api::Region);

    /// Pre-startup: write an org file to the temp directory.
    async fn apply_write_org_file(&mut self, filename: &str, content: &str);

    /// Pre-startup: create a directory.
    async fn apply_create_directory(&mut self, path: &str);

    /// Pre-startup: initialize git repository.
    async fn apply_git_init(&mut self);

    /// Pre-startup: initialize jj repository.
    async fn apply_jj_git_init(&mut self);

    /// Pre-startup: create a stale/corrupted .loro file.
    async fn apply_create_stale_loro(
        &mut self,
        org_filename: &str,
        corruption_type: crate::LoroCorruptionType,
    );

    /// Start the application.
    async fn apply_start_app(
        &mut self,
        ref_state: &ReferenceState,
        wait_for_ready: bool,
        enable_todoist: bool,
        enable_loro: bool,
    );

    /// Navigate to focus on a specific block within a region.
    async fn apply_navigate_focus(
        &mut self,
        region: holon_api::Region,
        block_id: &holon_api::EntityUri,
    );

    /// Navigate forward in the per-region navigation history.
    async fn apply_navigate_forward(&mut self, region: holon_api::Region);

    /// Navigate home (return to root) in a region.
    async fn apply_navigate_home(&mut self, region: holon_api::Region);

    /// Simulate app restart: clears last_projection and triggers re-sync.
    async fn apply_simulate_restart(&mut self, ref_state: &ReferenceState);

    /// Post-startup: create a new document and record the UUID mapping.
    async fn apply_create_document(&mut self, file_name: &str, ref_state: &ReferenceState);

    /// Post-startup: remove an active query watch.
    async fn apply_remove_watch(&mut self, query_id: &str);

    /// Post-startup: switch the current view.
    async fn apply_switch_view(&mut self, view_name: &str);

    /// Post-startup: run sequential query_and_watch operations to test for schema-lock bugs.
    async fn apply_concurrent_schema_init(&mut self);

    /// Post-startup: set up a query watch.
    async fn apply_setup_watch(
        &mut self,
        query_id: &str,
        query: &crate::pbt::query::TestQuery,
        language: holon_api::QueryLanguage,
    );

    /// Post-startup: toggle a block's task state via the StateToggle widget path.
    async fn apply_toggle_state(&mut self, block_id: &holon_api::EntityUri, new_state: &str);

    /// Post-startup: bulk add blocks to a document by writing an org file.
    async fn apply_bulk_external_add(
        &mut self,
        doc_uri: &holon_api::EntityUri,
        blocks: &[holon_api::block::Block],
        ref_state: &ReferenceState,
    );

    /// Post-startup: concurrent UI + external mutations.
    async fn apply_concurrent_mutations(
        &mut self,
        ui_mutation: crate::pbt::types::MutationEvent,
        external_mutation: crate::pbt::types::MutationEvent,
        ref_state: &ReferenceState,
    );

    /// Post-startup: apply a single UI or external mutation.
    async fn apply_apply_mutation(
        &mut self,
        event: crate::pbt::types::MutationEvent,
        ref_state: &ReferenceState,
    );

    /// Post-startup: trigger the "/" slash-command menu on a block and select "delete".
    async fn apply_trigger_slash_command(&mut self, block_id: &holon_api::EntityUri);

    /// Post-startup: indent the focused block (re-parent under previous sibling).
    async fn apply_indent(&mut self, block_id: &holon_api::EntityUri);

    /// Post-startup: outdent the focused block (move up to grandparent level).
    async fn apply_outdent(&mut self, block_id: &holon_api::EntityUri);

    /// Post-startup: move the focused block up (swap with previous sibling).
    async fn apply_move_up(&mut self, block_id: &holon_api::EntityUri);

    /// Post-startup: move the focused block down (swap with next sibling).
    async fn apply_move_down(&mut self, block_id: &holon_api::EntityUri);

    /// Post-startup: drag the source block onto the target, re-parenting source as
    /// a child of the target.
    async fn apply_drag_drop_block(
        &mut self,
        source: &holon_api::EntityUri,
        target: &holon_api::EntityUri,
    );

    /// Post-startup: click on a rendered block to focus it.
    async fn apply_click_block(
        &mut self,
        region: holon_api::Region,
        block_id: &holon_api::EntityUri,
    );

    /// Post-startup: split a block at a byte position.
    async fn apply_split_block(
        &mut self,
        block_id: &holon_api::EntityUri,
        position: usize,
        ref_state: &ReferenceState,
    );

    /// Post-startup: join a block into its previous sibling (or parent).
    async fn apply_join_block(
        &mut self,
        block_id: &holon_api::EntityUri,
        ref_state: &ReferenceState,
    );

    /// Post-startup: undo the last UI mutation.
    async fn apply_undo_last_mutation(&mut self, ref_state: &ReferenceState);

    /// Post-startup: redo the last undone mutation.
    async fn apply_redo(&mut self, ref_state: &ReferenceState);

    /// Post-startup: trigger IVM re-evaluation.
    async fn apply_emit_mcp_data(&mut self);

    /// Post-startup: focus an editable text block (atomic editor primitive).
    async fn apply_focus_editable_text(&mut self, block_id: &holon_api::EntityUri);

    /// Post-startup: move the active editor caret to a byte position.
    async fn apply_move_cursor(&mut self, byte_position: usize);

    /// Post-startup: type characters into the active editor.
    async fn apply_type_chars(&mut self, text: &str);

    /// Post-startup: delete characters backward in the active editor.
    async fn apply_delete_backward(&mut self, count: usize);

    /// Post-startup: press a structural key chord in the active editor.
    /// Takes `ref_state` so Enter (which dispatches `split_block`) can
    /// map the freshly-minted prod UUID back to the synthetic
    /// `block::split-N` slot the ref-state allocated.
    async fn apply_press_key(&mut self, chord: &holon_api::KeyChord, ref_state: &ReferenceState);

    /// Post-startup: arrow-key navigation from the focused block.
    async fn apply_arrow_navigate(
        &mut self,
        region: holon_api::Region,
        direction: holon_frontend::navigation::NavDirection,
        steps: u8,
        ref_state: &ReferenceState,
    );

    /// Post-startup: add a Loro-only peer instance sharing the primary's state.
    async fn apply_add_peer(&mut self);

    /// Post-startup: edit a block on a peer's LoroDoc directly.
    async fn apply_peer_edit(&mut self, peer_idx: usize, op: &crate::pbt::transitions::PeerEditOp);

    /// Post-startup: bidirectional sync between primary's LoroDoc and a peer.
    async fn apply_sync_with_peer(&mut self, peer_idx: usize);

    /// Post-startup: one-directional merge — peer's changes into primary.
    async fn apply_merge_from_peer(&mut self, peer_idx: usize);

    /// Post-startup: edit a block's LoroText container on a peer at character level.
    async fn apply_peer_char_edit(
        &mut self,
        peer_idx: usize,
        block_id: &str,
        op: &crate::pbt::transitions::TextOp,
    );

    /// Post-startup: pin a block to a sidebar (`focus_pin` op — LogSeq-style
    /// shift+click). No leader chord exists for this; the headless PBT
    /// dispatches the navigation op directly.
    async fn apply_pin_block(&mut self, region: holon_api::Region, block_id: &holon_api::EntityUri);

    /// Post-startup: close one open `navigation_history` row by id (`close`
    /// op — sidebar X button). Region-less.
    async fn apply_unpin_block(&mut self, history_id: i64);

    /// Post-startup: flip an `expand_toggle`'s `expanded` Mutable from
    /// false to true. Production binding is a chevron click; there is no
    /// backend operation — it's a frontend-state flip that drives
    /// `LazyReactiveSlot::materialize_if_gated` on the next render. The
    /// `E2ESut` impl walks the engine's reactive tree, finds the
    /// `expand_toggle` node whose `target_id` prop matches `block_id`,
    /// and calls `.expanded.set(true)`. Fails loud if the corpus grows a
    /// toggle render but the engine produces no matching node.
    async fn apply_expand_toggle(&mut self, block_id: &holon_api::EntityUri);

    /// Inverse of `apply_expand_toggle` — sets `.expanded` to false.
    /// Same walker; the `LazyReactiveSlot` cache is preserved by design
    /// so re-expand is instant. See
    /// `devlog/2026-05-15-lazy-expand-toggle-plan.md`.
    async fn apply_collapse_toggle(&mut self, block_id: &holon_api::EntityUri);
}

/// `declare_e2e_transitions!` — the only central code in the file-
/// per-transition pattern.
///
/// Wraps `declarative_enum_dispatch::enum_dispatch!` (which generates
/// the trait, the enum, and the trait-for-enum dispatch impl using
/// only `macro_rules!` — no proc macros) and adds the proptest-state-
/// machine strategy aggregator.
///
/// Adding a transition = create the file + add one line to the call.
#[macro_export]
macro_rules! declare_e2e_transitions {
    (
        $vis:vis enum $enum_name:ident {
            $($variant:ident($ty:ty)),* $(,)?
        }
    ) => {
        ::declarative_enum_dispatch::enum_dispatch!(
            #[allow(async_fn_in_trait)]
            pub trait E2ETransitionImpl: Clone + std::fmt::Debug + Send + Sync {
                fn preconditions(&self, state: &$crate::pbt::reference_state::ReferenceState)
                    -> ::validated::Validated<(), $crate::pbt::validation::Reason>;
                fn apply_to_ref(&self, state: &mut $crate::pbt::reference_state::ReferenceState);
                async fn apply_to_sut(&self, state: &$crate::pbt::reference_state::ReferenceState, sut: &mut dyn $crate::pbt::transition_dispatch::SutHandle);
                #[cfg(feature = "otel-testing")]
                fn expected_sql(&self, state: &$crate::pbt::reference_state::ReferenceState)
                    -> $crate::pbt::transition_budgets::ExpectedSql;
            }

            #[derive(Clone, Debug, ::serde::Serialize, ::serde::Deserialize)]
            $vis enum $enum_name {
                $( $variant($ty) ),*
            }
        );

        impl $enum_name {
            /// Variant name for trace logging and Markov-weighting in
            /// generators that bias on the previous transition kind.
            pub fn variant_name(&self) -> &'static str {
                match self {
                    $( Self::$variant(_) => stringify!($variant), )*
                }
            }
        }

        $vis fn aggregate_transitions(
            state: &$crate::pbt::reference_state::ReferenceState,
        ) -> ::proptest::strategy::BoxedStrategy<$enum_name> {
            use ::proptest::strategy::{Strategy, Union};
            use $crate::pbt::transition_dispatch::{E2ETransitionFactory, variant_weight_multiplier};

            let mut arms: Vec<(u32, ::proptest::strategy::BoxedStrategy<$enum_name>)> = Vec::new();

            $(
                match <$ty as E2ETransitionFactory>::weighted_generator(state) {
                    ::validated::Validated::Good((w, s)) => {
                        // Apply the per-variant `HOLON_PBT_WEIGHTS` multiplier
                        // here so individual transitions don't have to wire it.
                        // `0` is a legal multiplier — it removes the variant
                        // from the strategy; `Union::new_weighted` ignores
                        // zero-weight arms.
                        let multiplier = variant_weight_multiplier(stringify!($variant));
                        let final_weight = w.saturating_mul(multiplier);
                        if final_weight > 0 {
                            arms.push((final_weight, s.prop_map($enum_name::from).boxed()));
                        }
                    }
                    ::validated::Validated::Fail(reasons) => {
                        $crate::pbt::validation::record_rejection(
                            stringify!($variant),
                            &reasons,
                        );
                    }
                }
            )*

            assert!(
                !arms.is_empty(),
                "declare_e2e_transitions!: no transition applicable in state {state:?} \
                 — at least one variant must be unconditionally enabled."
            );
            Union::new_weighted(arms).boxed()
        }
    };
}
