import 'dart:async';

import 'package:flutter/foundation.dart' show setEquals;
import 'package:flutter/material.dart';
import '../src/rust/third_party/holon_api.dart' show Value;
import '../src/rust/third_party/holon_api/widget_spec.dart' show ResolvedRow;
// Freezed extensions are automatically available via 'part of' declarations
import '../src/rust/third_party/holon_api/render_types.dart';
import '../utils/value_converter.dart' show valueToDynamic;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:outliner_view/outliner_view.dart';
import '../src/rust/third_party/holon_api/streaming.dart'
    show BatchMapChangeWithMetadata, MapChange, MapChangePatterns;
import 'render_interpreter.dart';
import '../data/row_data_block_ops.dart';
import 'reactive_query_notifier.dart';
import 'list_item_widget.dart';
import '../providers/settings_provider.dart';
import '../styles/app_styles.dart';
import 'block_navigation_registry.dart';

/// Event type for CDC (Change Data Capture) streaming.
enum RowEventType { added, updated, removed }

class RowEvent {
  final RowEventType type;
  final String rowId;
  final ResolvedRow? data;

  const RowEvent({required this.type, required this.rowId, this.data});
}

/// Convert MapChange from Rust to RowEvent for widget consumption.
/// MapChange now carries ResolvedRow directly from the Rust FFI bridge.
RowEvent rowChangeToRowEvent(MapChange rowChange) {
  return rowChange.when(
    created: (resolvedRow, origin) {
      final id = _extractId(resolvedRow);
      if (id.isEmpty) {
        debugPrint(
          '[rowChangeToRowEvent] WARNING: Created event has empty ID!',
        );
      }
      return RowEvent(type: RowEventType.added, rowId: id, data: resolvedRow);
    },
    updated: (id, resolvedRow, origin) {
      final entityId = _extractId(resolvedRow, fallback: id);
      return RowEvent(
        type: RowEventType.updated,
        rowId: entityId,
        data: resolvedRow,
      );
    },
    fieldsChanged: (entityId, fields, origin) {
      // Build a partial ResolvedRow with only changed fields
      final data = <String, Value>{};
      for (final field in fields) {
        data[field.$1] = field.$3;
      }
      return RowEvent(
        type: RowEventType.updated,
        rowId: entityId,
        data: ResolvedRow(data: data),
      );
    },
    deleted: (id, origin) {
      return RowEvent(type: RowEventType.removed, rowId: id, data: null);
    },
  );
}

String _extractId(ResolvedRow row, {String fallback = ''}) {
  final idValue = row.data['id'];
  if (idValue == null) return fallback;
  return valueToDynamic(idValue)?.toString() ?? fallback;
}

// Provider is generated by @riverpod annotation in reactive_query_notifier.dart

/// Widget that renders query results with reactive CDC updates.
///
/// The backend provides the render expression (rootExpr) which tells
/// the frontend how to render the data. The frontend never knows about queries.
class ReactiveQueryWidget extends ConsumerWidget {
  /// Query key for CDC subscriptions (opaque string from backend).
  final String sql;

  /// Query parameters.
  final Map<String, dynamic> params;

  /// Root render expression from backend (always present).
  final RenderExpr rootExpr;

  /// Stream of change events from Rust.
  final Stream<BatchMapChangeWithMetadata>? changeStream;

  /// Initial data to populate the cache.
  final List<ResolvedRow>? initialData;

  /// Callback for executing operations (indent, outdent, etc.).
  final Future<void> Function(
    String entityName,
    String operationName,
    Map<String, dynamic> params,
  )?
  onOperation;

  /// Callback for syncing providers (e.g., Todoist).
  final Future<void> Function()? onSync;

  /// Optional parent context with screen-layout fields.
  final RenderContext? parentContext;

  const ReactiveQueryWidget({
    super.key,
    required this.sql,
    required this.params,
    required this.rootExpr,
    this.changeStream,
    this.initialData,
    this.onOperation,
    this.onSync,
    this.parentContext,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final queryKey = '${sql}_${params.toString()}';

    final queryParams = ReactiveQueryParams(
      queryKey: queryKey,
      sql: sql,
      params: params,
      changeStream: changeStream,
      initialData: initialData,
      onOperation: onOperation,
      onSync: onSync,
    );

    return _ReactiveQueryWidgetContent(
      queryKey: queryKey,
      queryParams: queryParams,
      rootExpr: rootExpr,
      onOperation: onOperation,
      onSync: onSync,
      parentContext: parentContext,
    );
  }
}

/// Wrapper for structural state that uses content-based equality.
class _StructuralState {
  final bool isLoading;
  final bool hasError;
  final Object? error;
  final Set<String> rowIds;

  const _StructuralState({
    required this.isLoading,
    required this.hasError,
    this.error,
    required this.rowIds,
  });

  @override
  bool operator ==(Object other) =>
      other is _StructuralState &&
      isLoading == other.isLoading &&
      hasError == other.hasError &&
      error == other.error &&
      setEquals(rowIds, other.rowIds);

  @override
  int get hashCode => Object.hash(isLoading, hasError, error, Object.hashAll(rowIds));
}

/// Internal widget that uses the provider
class _ReactiveQueryWidgetContent extends ConsumerWidget {
  final String queryKey;
  final ReactiveQueryParams queryParams;
  final RenderExpr rootExpr;
  final Future<void> Function(String, String, Map<String, dynamic>)?
  onOperation;
  final Future<void> Function()? onSync;
  final RenderContext? parentContext;

  const _ReactiveQueryWidgetContent({
    required this.queryKey,
    required this.queryParams,
    required this.rootExpr,
    this.onOperation,
    this.onSync,
    this.parentContext,
  });

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final structural = ref.watch(
      reactiveQueryStateProvider(queryParams).select(
        (asyncState) => asyncState.when(
          data: (state) => _StructuralState(
            isLoading: false,
            hasError: false,
            rowIds: state.rowCache.keys.toSet(),
          ),
          loading: () => const _StructuralState(
            isLoading: true,
            hasError: false,
            rowIds: {},
          ),
          error: (e, _) => _StructuralState(
            isLoading: false,
            hasError: true,
            error: e,
            rowIds: {},
          ),
        ),
      ),
    );

    if (structural.isLoading) {
      return const Center(child: CircularProgressIndicator());
    }

    if (structural.hasError) {
      return Center(child: Text('Error: ${structural.error}'));
    }

    if (structural.rowIds.isEmpty) {
      final asyncState = ref.read(reactiveQueryStateProvider(queryParams));
      return asyncState.maybeWhen(
        data: (queryState) => _buildEmpty(ref, queryState),
        orElse: () => const Center(child: Text('No data')),
      );
    }

    final asyncState = ref.read(reactiveQueryStateProvider(queryParams));
    return asyncState.maybeWhen(
      data: (queryState) => _buildFromCache(ref, queryState),
      orElse: () => const SizedBox.shrink(),
    );
  }

  /// Build UI from cached row data.
  Widget _buildFromCache(WidgetRef ref, ReactiveQueryState queryState) {
    final interpreter = RenderInterpreter();
    final colors = ref.watch(appColorsProvider);

    return rootExpr.when(
      functionCall: (name, args, _) {
        if (name == 'list') {
          return _buildListView(ref, queryState, args, interpreter, colors);
        }
        if (name == 'outline') {
          return _buildOutlineView(ref, queryState, args, interpreter, colors);
        }
        if (name == 'tree') {
          return _buildTreeView(ref, queryState, args, interpreter, colors);
        }
        if (name == 'table') {
          return _buildTableView(ref, queryState, args, interpreter, colors);
        }
        return _buildSingleItem(queryState, rootExpr, interpreter, colors);
      },
      blockRef: (blockId) => Text('[BlockRef: $blockId]'),
      columnRef: (_) =>
          _buildSingleItem(queryState, rootExpr, interpreter, colors),
      literal: (_) =>
          _buildSingleItem(queryState, rootExpr, interpreter, colors),
      binaryOp: (_, __, ___) =>
          _buildSingleItem(queryState, rootExpr, interpreter, colors),
      array: (_) => _buildSingleItem(queryState, rootExpr, interpreter, colors),
      object: (_) =>
          _buildSingleItem(queryState, rootExpr, interpreter, colors),
    );
  }

  /// Build empty state.
  Widget _buildEmpty(WidgetRef ref, ReactiveQueryState queryState) {
    if (onSync != null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'No data',
              style: TextStyle(fontSize: 16, color: Colors.grey),
            ),
            const SizedBox(height: 16),
            ElevatedButton.icon(
              onPressed: queryState.isSyncing
                  ? null
                  : () => ref
                        .read(reactiveQueryStateProvider(queryParams).notifier)
                        .sync(),
              icon: queryState.isSyncing
                  ? const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    )
                  : const Icon(Icons.sync),
              label: Text(
                queryState.isSyncing ? 'Syncing...' : 'Sync from Todoist',
              ),
            ),
          ],
        ),
      );
    }
    return const Center(child: Text('No data'));
  }

  /// Build ListView with virtualization and keyed widgets.
  Widget _buildListView(
    WidgetRef ref,
    ReactiveQueryState queryState,
    List<Arg> listArgs,
    RenderInterpreter interpreter,
    AppColors colors,
  ) {
    final itemExpr = listArgs
        .firstWhere(
          (arg) => arg.name == 'item_template',
          orElse: () =>
              throw ArgumentError('list() requires "item_template" argument'),
        )
        .value;

    return BlockNavigationRegistry(
      orderedIds: queryState.rowOrder,
      child: ListView.builder(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
        itemCount: queryState.rowOrder.length,
        itemBuilder: (context, index) {
          final rowId = queryState.rowOrder[index];

          ResolvedRow? previousRow;
          if (index > 0) {
            final previousRowId = queryState.rowOrder[index - 1];
            previousRow = queryState.rowCache[previousRowId];
          }

          return ListItemWidget(
            key: ValueKey(rowId),
            rowId: rowId,
            queryParams: queryParams,
            interpreter: interpreter,
            itemExpr: itemExpr,
            onOperation: onOperation,
            rowIndex: index,
            previousRow: previousRow,
          );
        },
      ),
    );
  }

  /// Build AnimatedTreeView from tree() function.
  Widget _buildTreeView(
    WidgetRef ref,
    ReactiveQueryState queryState,
    List<Arg> treeArgs,
    RenderInterpreter interpreter,
    AppColors colors,
  ) {
    final parentIdArg = treeArgs.firstWhere(
      (arg) => arg.name == 'parent_id',
      orElse: () => throw ArgumentError('tree() requires "parent_id" argument'),
    );
    final sortKeyArg = treeArgs.firstWhere(
      (arg) => arg.name == 'sortkey' || arg.name == 'sort_key',
      orElse: () => throw ArgumentError(
        'tree() requires "sortkey" or "sort_key" argument',
      ),
    );

    final parentIdColumn = _evaluateColumnName(parentIdArg.value);
    final sortKeyColumn = _evaluateColumnName(sortKeyArg.value);

    final firstRow = queryState.rowCache.values.isNotEmpty
        ? queryState.rowCache.values.first
        : null;

    final entityName =
        _extractEntityName() ?? _extractStringField(firstRow, 'entity_name');
    if (entityName == null) {
      throw StateError(
        'tree() requires entity_name but none found. '
        'Either add operations to the render spec or include an entity_name column in the query.',
      );
    }

    final treeContext = RenderContext(
      resolvedRow: firstRow,
      onOperation: onOperation,
      entityName: entityName,
      rowCache: queryState.rowCache,
      parentIdColumn: parentIdColumn,
      sortKeyColumn: sortKeyColumn,
      colors: colors,
      queryParams: queryParams,
    );

    return interpreter.build(rootExpr, treeContext);
  }

  /// Build TableView from table() function.
  Widget _buildTableView(
    WidgetRef ref,
    ReactiveQueryState queryState,
    List<Arg> tableArgs,
    RenderInterpreter interpreter,
    AppColors colors,
  ) {
    final tableContext = RenderContext(
      rowCache: queryState.rowCache,
      onOperation: onOperation,
      colors: colors,
    );

    return interpreter.build(rootExpr, tableContext);
  }

  /// Build OutlinerListView from outline() function.
  Widget _buildOutlineView(
    WidgetRef ref,
    ReactiveQueryState queryState,
    List<Arg> outlineArgs,
    RenderInterpreter interpreter,
    AppColors colors,
  ) {
    final parentIdArg = outlineArgs.firstWhere(
      (arg) => arg.name == 'parent_id',
      orElse: () =>
          throw ArgumentError('outline() requires "parent_id" argument'),
    );
    final sortKeyArg = outlineArgs.firstWhere(
      (arg) => arg.name == 'sortkey' || arg.name == 'sort_key',
      orElse: () => throw ArgumentError(
        'outline() requires "sortkey" or "sort_key" argument',
      ),
    );
    final itemTemplateArg = outlineArgs.firstWhere(
      (arg) => arg.name == 'item_template' || arg.name == 'item',
      orElse: () => throw ArgumentError(
        'outline() requires "item_template" or "item" argument',
      ),
    );

    final parentIdColumn = _evaluateColumnName(parentIdArg.value);
    final sortKeyColumn = _evaluateColumnName(sortKeyArg.value);

    final firstRow = queryState.rowCache.values.isNotEmpty
        ? queryState.rowCache.values.first
        : null;
    final entityName =
        _extractEntityName() ?? _extractStringField(firstRow, 'entity_name');
    if (entityName == null) {
      throw StateError(
        'outline() requires entity_name but none found. '
        'Either add operations to the render spec or include an entity_name column in the query.',
      );
    }

    final notifier = ref.read(reactiveQueryStateProvider(queryParams).notifier);
    var blockOps = queryState.blockOps;
    if (blockOps == null) {
      blockOps = RowDataBlockOps(
        rowCache: queryState.rowCache,
        parentIdColumn: parentIdColumn,
        sortKeyColumn: sortKeyColumn,
        entityName: entityName,
        onOperation: onOperation,
      );
      notifier.setBlockOps(blockOps);
    }

    for (final entry in queryState.rowCache.entries) {
      blockOps.updateRowCache(entry.key, entry.value);
    }

    final opsProvider = Provider<BlockOps<ResolvedRow>>((ref) {
      return blockOps!;
    });

    final notifierProvider =
        NotifierProvider<
          OutlinerNotifier<ResolvedRow>,
          OutlinerState<ResolvedRow>
        >(() {
          return OutlinerNotifier<ResolvedRow>(blockOps!);
        });

    final itemTemplate = itemTemplateArg.value;

    // Compute DFS order for outline navigation
    final orderedIds = _computeOutlineDfsOrder(queryState.rowCache, parentIdColumn, sortKeyColumn);

    return ProviderScope(
      overrides: [opsProvider.overrideWithValue(blockOps)],
      child: BlockNavigationRegistry(
        orderedIds: orderedIds,
        child: OutlinerListView<ResolvedRow>(
          opsProvider: opsProvider,
          notifierProvider: notifierProvider,
          config: const OutlinerConfig(
            keyboardShortcutsEnabled: true,
            padding: EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          ),
          blockBuilder: (buildContext, block) {
            final registry = BlockNavigationRegistry.maybeOf(buildContext);
            final blockId = _extractId(block);
            final blockContext = RenderContext(
              resolvedRow: block,
              onOperation: onOperation,
              entityName: entityName,
              rowCache: queryState.rowCache,
              parentIdColumn: parentIdColumn,
              sortKeyColumn: sortKeyColumn,
              colors: colors,
              onRegisterEditable: registry != null && blockId.isNotEmpty
                  ? (fn, ctrl) => registry.register(blockId, fn, ctrl)
                  : null,
              onNavigateUp: registry != null && blockId.isNotEmpty
                  ? (col) => registry.navigate(blockId, AxisDirection.up, col)
                  : null,
              onNavigateDown: registry != null && blockId.isNotEmpty
                  ? (col) => registry.navigate(blockId, AxisDirection.down, col)
                  : null,
            );
            return interpreter.build(itemTemplate, blockContext);
          },
        ),
      ),
    );
  }

  /// Evaluate column name from RenderExpr
  String _evaluateColumnName(RenderExpr expr) {
    return expr.when(
      columnRef: (name) => name,
      literal: (value) {
        final dynamicValue = valueToDynamic(value);
        if (dynamicValue is String) {
          return dynamicValue;
        }
        throw ArgumentError(
          'Column name must be a string literal or column reference',
        );
      },
      functionCall: (_, __, ___) =>
          throw ArgumentError('Column name cannot be a function call'),
      blockRef: (_) =>
          throw ArgumentError('Column name cannot be a block ref'),
      binaryOp: (_, __, ___) =>
          throw ArgumentError('Column name cannot be a binary operation'),
      array: (_) => throw ArgumentError('Column name cannot be an array'),
      object: (_) => throw ArgumentError('Column name cannot be an object'),
    );
  }

  /// Extract entity name from render spec or operations
  String? _extractEntityName() {
    return rootExpr.when(
      functionCall: (name, args, operations) {
        if (operations.isNotEmpty) {
          return operations.first.descriptor.entityName.field0.isNotEmpty
              ? operations.first.descriptor.entityName.field0
              : null;
        }
        return null;
      },
      blockRef: (_) => null,
      columnRef: (_) => null,
      literal: (_) => null,
      binaryOp: (_, __, ___) => null,
      array: (_) => null,
      object: (_) => null,
    );
  }

  /// Build single item (non-list rendering).
  Widget _buildSingleItem(
    ReactiveQueryState queryState,
    RenderExpr expr,
    RenderInterpreter interpreter,
    AppColors colors,
  ) {
    if (queryState.rowCache.isEmpty) {
      return const Center(child: Text('No data'));
    }

    final rowId = queryState.rowOrder.first;
    final row = queryState.rowCache[rowId]!;

    final renderContext = RenderContext(
      resolvedRow: row,
      onOperation: onOperation,
      rowIndex: 0,
      previousRow: null,
      colors: colors,
      rowCache: queryState.rowCache,
      isScreenLayout: parentContext?.isScreenLayout ?? false,
      drawerState: parentContext?.drawerState,
      sidebarWidth: parentContext?.sidebarWidth,
      rightDrawerState: parentContext?.rightDrawerState,
      rightSidebarWidth: parentContext?.rightSidebarWidth,
    );

    return interpreter.build(expr, renderContext);
  }

  /// Compute DFS-ordered list of block IDs from row cache for outline navigation.
  static List<String> _computeOutlineDfsOrder(
    Map<String, ResolvedRow> rowCache,
    String parentIdColumn,
    String sortKeyColumn,
  ) {
    final childrenOf = <String, List<String>>{};
    final roots = <String>[];

    for (final entry in rowCache.entries) {
      final id = entry.key;
      final parentVal = entry.value.data[parentIdColumn];
      final parentId = parentVal != null ? valueToDynamic(parentVal)?.toString() : null;

      if (parentId == null || parentId.isEmpty || !rowCache.containsKey(parentId)) {
        roots.add(id);
      } else {
        childrenOf.putIfAbsent(parentId, () => []).add(id);
      }
    }

    int sortKey(String id) {
      final row = rowCache[id];
      if (row == null) return 0;
      final val = row.data[sortKeyColumn];
      if (val == null) return 0;
      final dyn = valueToDynamic(val);
      if (dyn is num) return dyn.toInt();
      return 0;
    }

    roots.sort((a, b) => sortKey(a).compareTo(sortKey(b)));
    for (final children in childrenOf.values) {
      children.sort((a, b) => sortKey(a).compareTo(sortKey(b)));
    }

    final result = <String>[];
    void dfs(String id) {
      result.add(id);
      final children = childrenOf[id];
      if (children != null) {
        for (final child in children) {
          dfs(child);
        }
      }
    }
    for (final root in roots) {
      dfs(root);
    }
    return result;
  }

  /// Extract a string field from a ResolvedRow's data map.
  static String? _extractStringField(ResolvedRow? row, String field) {
    if (row == null) return null;
    final value = row.data[field];
    if (value == null) return null;
    return valueToDynamic(value)?.toString();
  }
}
