/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Opfs {

}

export declare class OpfsFile {

}

export declare function completeOpfs(completionNo: number, result: number): void

/** Execute a DDL/DML statement, returning affected row count. */
export declare function dbExecute(sql: string): number

/**
 * Execute a SELECT and return rows as newline-delimited `|`-joined strings.
 * Phase 2 only needs a string round-trip to prove persistence; a proper
 * typed JSON path lands in Phase 3 alongside the BackendEngine wiring.
 */
export declare function dbQuery(sql: string): string

/**
 * Cancel a subscription created by `engine_watch_view`. No-op if the
 * stream already ended naturally.
 */
export declare function engineDropSubscription(handle: number): void

/**
 * Execute a holon operation and return the result as a JSON string.
 *
 * - `entity`: entity name (e.g. `"block"`)
 * - `op`: operation name (e.g. `"update"`, `"delete"`, `"create"`)
 * - `params_json`: JSON-encoded `{ key: value }` params map
 *
 * Returns the JSON-serialized `Option<Value>` result: `"null"` when
 * the operation returns nothing, or a JSON-encoded `Value` otherwise.
 */
export declare function engineExecuteOperation(entity: string, op: string, paramsJson: string): string

export declare function engineExecuteQuery(sql: string): string

/**
 * Execute a DDL/DML statement. Returns `()` — affected row count is
 * not exposed yet (see `backend::execute_sql`).
 */
export declare function engineExecuteSql(sql: string): void

export declare function engineInit(dbPath: string): void

/**
 * B2 validation: run `watch_live` on the root layout block and return
 * the root node variant tag.
 */
export declare function engineReactiveCheck(): string

/**
 * Switch the active render variant for a watched block. Errors if the
 * block is not currently being watched (see
 * `ReactiveEngine::set_variant`).
 */
export declare function engineSetVariant(blockId: string, variant: string): void

/**
 * Drive the current-thread runtime for `budget_ms` milliseconds so
 * spawned tasks (notably `watch_view` drains) can progress. Must be
 * called periodically from JS (`setInterval` / `requestAnimationFrame`
 * / after every RPC) — nothing runs without a `block_on` caller.
 */
export declare function engineTick(budgetMs: number): void

/**
 * Start watching `block_id` for `ViewModel` changes.
 *
 * `callback` receives a single string argument — the full JSON-serialized
 * `ViewModel` snapshot — on every structural or data change. Bursts
 * are coalesced to the latest value.
 *
 * Returns a `u32` handle to pass to `engine_drop_subscription`. The
 * handle is registered BEFORE the drain task is spawned, so JS can
 * rely on the returned value without any ordering dance.
 */
export declare function engineWatchView(blockId: string, callback: (arg0: string) => void): number

/**
 * turso-db in the the browser requires explicit thread pool initialization
 * so, we just put no-op task on the thread pool and force emnapi to allocate web worker
 */
export declare function initThreadPool(): Promise<unknown>

/**
 * Open (or create) a Turso database at `path` backed by the OPFS IO shim.
 * Re-opening replaces any existing handle. Phase 2 does not yet support
 * multiple databases.
 */
export declare function openDb(path: string): void

/**
 * H4 step 1 — tokio timers work inside a `#[napi] async fn`.
 *
 * Sleeps 50ms on whatever runtime napi's `tokio_rt` feature installs, then
 * returns a greeting. If the sleep traps, we know napi's ambient runtime
 * is not driving tokio timers on `wasm32-wasip1-threads` and Phase 3 has
 * to fall back to the current-thread/`block_on` path.
 */
export declare function ping(s: string): Promise<string>

/**
 * H4 step 2 — current-thread runtime spawns and joins tasks.
 *
 * **Original plan:** validate `Builder::new_multi_thread()`. **Result:**
 * FALSIFIED at compile time. tokio 1.51 explicitly refuses to compile
 * `rt-multi-thread` on any wasm target via:
 *
 * ```text
 * compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");
 * ```
 *
 * (See `tokio/src/lib.rs` line 478 in the installed crate version.) That
 * means the worker MUST drive `BackendEngine` from a current-thread runtime.
 * This function builds one and asserts that `tokio::spawn` + `tokio::time`
 * still work on a current-thread driver — which is the entire fallback path
 * the plan called out under H4. If this also fails, the whole architecture
 * has to rethink async.
 *
 * Intentionally sync (`#[napi]` without `async`) so the runtime we
 * build here is the one under test, not napi's ambient one.
 */
export declare function spawnCheck(): string
