//! Org parse-render fixed-point slice PBT — proves the org parser and
//! renderer form a round-trip that converges to a fixed point after one
//! parse-render cycle, and that no structural information (parent edges,
//! content, tags, properties) is dropped on the way through.
//!
//! Slice composition: `{Vec<Block>, OrgRenderer, parse_org_file}`. No
//! Loro, no Turso, no editor, no UI, no async, no proptest-state-machine
//! plumbing — plain proptest because the invariant is per-state, not
//! per-trace, and the bug class (parse↔render fidelity) is structural,
//! not temporal.
//!
//! Bug class targeted (per MEMORY entries):
//! - `:edge_abstraction:` tag drop on round-trip (May 2026)
//! - `inv-displayed-text` 3-extra-chars from WriteOrgFile parser gaps
//! - Org renderer matview-lag class — surfaces here as content drift
//!
//! Each case:
//! 1. Generates a random tree of blocks (1..=8 blocks, depth ≤ 4) with
//!    contents/tags/properties drawn from small alphabets.
//! 2. Renders the tree to org text.
//! 3. Parses the org text back to blocks.
//! 4. Re-renders the parsed blocks.
//! 5. Asserts: re-render equals first render (fixed point), and the
//!    parsed structure matches the input structurally.

#![cfg(feature = "pbt")]

use std::collections::BTreeSet;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use holon_api::{Block, EntityUri, Value};
use holon_orgmode::models::OrgDocumentExt;
use holon_orgmode::org_renderer::OrgRenderer;
use holon_orgmode::parser::parse_org_file;
use proptest::prelude::*;

// ─────────────────────────────────────────────────────────────────
// Tree model — generated by proptest, lowered to Vec<Block>
// ─────────────────────────────────────────────────────────────────

/// Tag alphabet kept small so any drop shows up quickly. Includes
/// `edge_abstraction` because that's the May 2026 regression case.
const TAG_ALPHABET: &[&str] = &["work", "urgent", "edge_abstraction", "draft"];

/// Property keys we exercise. `TODO`/`PRIORITY` go through the
/// renderer's dedicated headline-prefix path; `MY_KEY` goes through
/// the generic :PROPERTIES: drawer path. Both must round-trip.
const PROP_KEYS: &[&str] = &["MY_KEY", "ANOTHER"];

#[derive(Debug, Clone)]
struct GenBlock {
    /// Bare ID (we'll wrap with `block:` at lowering time).
    id: String,
    content: String,
    tags: Vec<String>,
    /// Generic drawer properties (NOT ID — that's set automatically).
    properties: Vec<(String, String)>,
    /// `Some(keyword)` → TODO keyword goes on the headline. Must be one
    /// of the default active/done keywords so the parser recognises it
    /// without a `#+TODO:` config line.
    todo: Option<String>,
    children: Vec<GenBlock>,
}

fn arb_word() -> impl Strategy<Value = String> {
    "[a-z]{1,8}".prop_map(|s| s)
}

fn arb_content() -> impl Strategy<Value = String> {
    // Multi-word headline content, ASCII only — avoids confounding the
    // round-trip with Unicode normalization issues that aren't this
    // slice's concern.
    prop::collection::vec(arb_word(), 1..=3).prop_map(|ws| ws.join(" "))
}

fn arb_tags() -> impl Strategy<Value = Vec<String>> {
    prop::collection::vec(
        prop::sample::select(TAG_ALPHABET.to_vec()).prop_map(|s| s.to_string()),
        0..=3,
    )
    .prop_map(|mut v| {
        // Tags must be unique per block.
        v.sort();
        v.dedup();
        v
    })
}

fn arb_properties() -> impl Strategy<Value = Vec<(String, String)>> {
    prop::collection::vec(
        (
            prop::sample::select(PROP_KEYS.to_vec()).prop_map(|s| s.to_string()),
            arb_word(),
        ),
        0..=2,
    )
    .prop_map(|mut v| {
        // One value per key — the renderer can't preserve duplicates.
        let mut seen = BTreeSet::new();
        v.retain(|(k, _)| seen.insert(k.clone()));
        v
    })
}

fn arb_todo() -> impl Strategy<Value = Option<String>> {
    prop_oneof![
        4 => Just(None),
        1 => Just(Some("TODO".to_string())),
        1 => Just(Some("DONE".to_string())),
    ]
}

/// Recursive tree generator. Each call burns one slot from `budget`
/// and recurses for children with whatever remains.
fn arb_block(
    next_id: &Arc<Mutex<u64>>,
    depth: usize,
    max_depth: usize,
    max_children: usize,
) -> BoxedStrategy<GenBlock> {
    let next_id_clone = next_id.clone();
    let leaf = (arb_content(), arb_tags(), arb_properties(), arb_todo()).prop_map(
        move |(content, tags, properties, todo)| {
            let id_n = {
                let mut g = next_id_clone.lock().unwrap();
                let n = *g;
                *g += 1;
                n
            };
            GenBlock {
                id: format!("n{id_n}"),
                content,
                tags,
                properties,
                todo,
                children: Vec::new(),
            }
        },
    );

    if depth >= max_depth {
        return leaf.boxed();
    }

    leaf.prop_recursive(
        (max_depth - depth) as u32,
        max_children as u32,
        max_children as u32,
        move |inner| {
            (
                inner.clone(),
                prop::collection::vec(inner, 0..=max_children),
            )
                .prop_map(|(mut parent, kids)| {
                    parent.children = kids;
                    parent
                })
        },
    )
    .boxed()
}

/// Top-level tree: a doc with 1..=4 top-level headlines, each up to depth 3.
fn arb_tree() -> impl Strategy<Value = Vec<GenBlock>> {
    let next_id = Arc::new(Mutex::new(0u64));
    let next_id_clone = next_id.clone();
    prop::collection::vec(arb_block(&next_id, 0, 3, 2), 1..=4).prop_map(move |tops| {
        let _ = &next_id_clone; // keep alive for the duration of the case
        tops
    })
}

// ─────────────────────────────────────────────────────────────────
// Lowering: GenBlock tree → Vec<Block>
// ─────────────────────────────────────────────────────────────────

const DOC_ID: &str = "rtdoc";

fn doc_uri() -> EntityUri {
    EntityUri::block(DOC_ID)
}

fn doc_path() -> PathBuf {
    PathBuf::from("/test/rtdoc.org")
}

fn doc_root() -> PathBuf {
    PathBuf::from("/test")
}

fn make_doc_block() -> Block {
    let mut doc = Block::new_text(
        doc_uri(),
        EntityUri::no_parent(),
        "rtdoc".to_string(), // title
    );
    doc.set_page(true);
    doc.set_file_title(Some("rtdoc".to_string()));
    doc
}

fn lower_to_blocks(tops: &[GenBlock]) -> Vec<Block> {
    let mut out = Vec::new();
    // Sort keys — deterministic, increasing across siblings, hex digits
    // so they're compatible with the FractionalIndex domain the rest of
    // the system uses.
    fn lower(out: &mut Vec<Block>, parent_uri: &EntityUri, kids: &[GenBlock], sort_prefix: &str) {
        for (i, k) in kids.iter().enumerate() {
            // Sort key: prefix + 2-hex-digit per-sibling index, upper-case.
            // Generated keys live inside the FractionalIndex sortable range.
            let sort_key = format!("{sort_prefix}{:02X}", 0x10 + (i as u8));
            let uri = EntityUri::block(&k.id);
            let mut b = Block::new_text(uri.clone(), parent_uri.clone(), k.content.clone());
            b.set_property("ID", Value::String(k.id.clone()));
            for (key, val) in &k.properties {
                b.set_property(key.clone(), Value::String(val.clone()));
            }
            if let Some(kw) = &k.todo {
                b.set_property("TODO", Value::String(kw.clone()));
            }
            b.tags = k.tags.clone().into();
            b.sort_key = sort_key.clone();
            out.push(b);
            lower(out, &uri, &k.children, &format!("{sort_key}_"));
        }
    }
    lower(&mut out, &doc_uri(), tops, "A0_");
    out
}

// ─────────────────────────────────────────────────────────────────
// Structural-equivalence assertion
// ─────────────────────────────────────────────────────────────────

/// Parser-injected derived keys. The parser materialises these on
/// every parsed block (`level`, `sequence`) or transfers them from the
/// headline prefix into typed slots (`task_state`, `priority`). We
/// normalise both sides to a comparable shape rather than chase each
/// derived field with a dedicated equality.
const PARSER_DERIVED_KEYS: &[&str] = &[
    "level",
    "sequence",
    "task_state",
    "priority",
    "scheduled",
    "deadline",
];

#[derive(Debug, PartialEq, Eq, Ord, PartialOrd)]
struct StructRow {
    id: String,
    parent: String,
    content: String,
    tags: Vec<String>,
    /// User-set properties only. Excludes renderer-internal `_*` keys,
    /// `ID` (asserted via row id), `TAGS` (asserted via `tags`), and
    /// parser-derived fields (see [`PARSER_DERIVED_KEYS`]).
    properties: Vec<(String, String)>,
    /// Normalised TODO keyword. Input sets `properties["TODO"]`; the
    /// parser exposes it as `task_state` — we collapse both forms here
    /// so the comparison is form-agnostic.
    todo: Option<String>,
}

fn value_to_string(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Integer(n) => n.to_string(),
        Value::Float(f) => f.to_string(),
        Value::Boolean(b) => b.to_string(),
        _ => format!("{v:?}"),
    }
}

fn structural_view(doc: &Block, blocks: &[Block]) -> Vec<StructRow> {
    let mut rows: Vec<StructRow> = blocks
        .iter()
        .map(|b| {
            // `Tags` is a `BTreeSet`, so iteration is already canonically
            // ordered — collect to the `Vec<String>` the StructRow expects.
            let tags: Vec<String> = b.tags.iter().cloned().collect();
            let mut properties: Vec<(String, String)> = b
                .properties
                .iter()
                .filter(|(k, _)| {
                    let k: &str = k;
                    !k.starts_with('_')
                        && k != "ID"
                        && k != "TAGS"
                        && k != "TODO"
                        && !PARSER_DERIVED_KEYS.contains(&k)
                })
                .map(|(k, v)| (k.clone(), value_to_string(v)))
                .collect();
            properties.sort();
            let todo = b
                .properties
                .get("TODO")
                .or_else(|| b.properties.get("task_state"))
                .map(value_to_string);
            StructRow {
                id: b.id.id().to_string(),
                parent: b.parent_id.id().to_string(),
                content: b.content.clone(),
                tags,
                properties,
                todo,
            }
        })
        .collect();
    rows.sort();
    let _ = doc; // doc identity asserted separately via #+ID header
    rows
}

// ─────────────────────────────────────────────────────────────────
// One round-trip case
// ─────────────────────────────────────────────────────────────────

fn run_case(tops: &[GenBlock]) -> Result<(), TestCaseError> {
    let doc = make_doc_block();
    let blocks = lower_to_blocks(tops);

    let path = doc_path();
    let root = doc_root();

    // First render — this is the canonical org text.
    let rendered_1 = OrgRenderer::render_document(&doc, &blocks, &path, &doc_uri());

    // Parse it back.
    let parsed =
        parse_org_file(&path, &rendered_1, &EntityUri::no_parent(), &root).map_err(|e| {
            TestCaseError::fail(format!("parse failed: {e}\n--- TEXT ---\n{rendered_1}"))
        })?;

    // Re-render the parsed result.
    let rendered_2 =
        OrgRenderer::render_document(&parsed.document, &parsed.blocks, &path, &doc_uri());

    // Fixed-point invariant.
    if rendered_1 != rendered_2 {
        return Err(TestCaseError::fail(format!(
            "[inv-org-render-fixed-point] render→parse→render diverged\n--- FIRST ---\n{rendered_1}\n--- SECOND ---\n{rendered_2}"
        )));
    }

    // Structural invariant — parse must preserve the tree we put in.
    let want = structural_view(&doc, &blocks);
    let got = structural_view(&parsed.document, &parsed.blocks);
    if want != got {
        return Err(TestCaseError::fail(format!(
            "[inv-org-parse-preserves-structure] parsed structure ≠ input\n--- WANT ---\n{want:#?}\n--- GOT ---\n{got:#?}\n--- RENDERED ---\n{rendered_1}"
        )));
    }

    Ok(())
}

// ─────────────────────────────────────────────────────────────────
// proptest entrypoint
// ─────────────────────────────────────────────────────────────────

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 512,
        max_shrink_iters: 200,
        .. ProptestConfig::default()
    })]

    /// Org parse-render fixed-point.
    #[test]
    fn org_roundtrip_fixed_point(tops in arb_tree()) {
        run_case(&tops)?;
    }
}

// ─────────────────────────────────────────────────────────────────
// Sanity tests — fixed inputs that pin the bug classes named in MEMORY
// so a regression in the parser/renderer shows up as a unit-test
// failure, not just a PBT flake.
// ─────────────────────────────────────────────────────────────────

#[test]
fn sanity_edge_abstraction_tag_roundtrips() {
    // The May 2026 :edge_abstraction: drop case.
    let tops = vec![GenBlock {
        id: "n0".into(),
        content: "headline".into(),
        tags: vec!["edge_abstraction".into()],
        properties: vec![],
        todo: None,
        children: vec![],
    }];
    run_case(&tops).expect("edge_abstraction tag must survive round-trip");
}

#[test]
fn sanity_property_drawer_roundtrips() {
    let tops = vec![GenBlock {
        id: "n0".into(),
        content: "headline".into(),
        tags: vec![],
        properties: vec![("MY_KEY".into(), "hello".into())],
        todo: None,
        children: vec![],
    }];
    run_case(&tops).expect("drawer property must survive round-trip");
}

#[test]
fn sanity_todo_keyword_roundtrips() {
    let tops = vec![GenBlock {
        id: "n0".into(),
        content: "task".into(),
        tags: vec![],
        properties: vec![],
        todo: Some("TODO".into()),
        children: vec![],
    }];
    run_case(&tops).expect("TODO keyword must survive round-trip");
}

#[test]
fn sanity_nested_tree_roundtrips() {
    let tops = vec![GenBlock {
        id: "n0".into(),
        content: "parent".into(),
        tags: vec![],
        properties: vec![],
        todo: None,
        children: vec![GenBlock {
            id: "n1".into(),
            content: "child".into(),
            tags: vec!["work".into()],
            properties: vec![],
            todo: None,
            children: vec![],
        }],
    }];
    run_case(&tops).expect("nested tree must survive round-trip");
}
