//! Stream-based datasource traits for external system integration
//!
//! This module provides traits for reactive sync architecture where:
//! - DataSources provide read-only access (from cache)
//! - CrudOperationss provide write operations (fire-and-forget to external systems)
//! - Changes flow via ChangeNotifications streams from SyncProviders to Caches
//! - QueryableCache wraps datasources and implements both read and write traits
//!
//! On WASM, futures are often !Send (because they wrap JS promises). // ALLOW(compatibility): genuine WASM-vs-native target distinction, not a removable shim
//! `MaybeSendSync` and `#[async_trait(?Send)]` relax thread-safety
//! requirements so a single trait definition compiles on both targets.

use async_trait::async_trait;

use crate::core::queryable_cache::QueryableCache;
use crate::core::traits::{IntoEntity, TryFromEntity};

// Re-export core traits from holon-core
pub use holon_core::{
    BlockDataSourceHelpers, BlockEntity, BlockMaintenanceHelpers, BlockOperations,
    BlockQueryHelpers, CompletionStateInfo, CrudOperations, DataSource, FieldDelta, MarkOperations,
    MaybeSendSync, MoveOperations, OperationRegistry, OperationResult, RenameOperations, Result,
    TaskEntity, TaskOperations, TextOperations, UndoAction, UnknownOperationError,
};

// Re-export undo types for external crates
pub use holon_api::Operation;
pub use holon_core::undo::UndoStack;

// Re-export macro-generated operation dispatch functions from holon-core
pub use holon_core::{
    __operations_block_operations, __operations_crud_operations, __operations_mark_operations,
    __operations_move_operations, __operations_rename_operations, __operations_task_operations,
    __operations_text_operations,
};

// Re-export macro-generated dispatch functions for HasCache trait (defined in this crate)
// This will be auto-generated by #[operations_trait] on HasCache below

// Re-export OperationDescriptor and OperationParam from holon-api
pub use holon_api::{OperationDescriptor, OperationParam};

// Re-export Change types from api (which re-exports from holon-api)
pub use crate::api::{Change, ChangeOrigin, StreamPosition};

// Result and UnknownOperationError are now defined in holon-core and re-exported above.

// DataSource, BlockDataSourceHelpers, BlockOperations, and TaskOperations
// are now defined in holon-core and re-exported above.

// All traits (DataSource, BlockDataSourceHelpers, BlockOperations, TaskOperations)
// and their blanket implementations are now defined in holon-core and re-exported above.

// BlockOperations and BlockDataSourceHelpers require explicit opt-in per type.
// All default implementations live in holon-core traits.

/// Type-independent operation provider trait
///
/// Supports both local (cache-based) and external (API-based) providers.
/// Operations are self-describing via OperationDescriptor metadata.
///
/// # Design
/// - **OperationProvider = QueryableCache + dispatch layer**: Routes `execute_operation` to
///   CRUD operations (create/set_field/delete) or custom operations
/// - **Composite dispatcher pattern**: OperationDispatcher itself implements OperationProvider,
///   allowing composition
/// - **Provider registry discovery**: Providers expose introspection via `operations()`,
///   allowing OperationDispatcher to discover all providers at runtime via DI
///
/// # Examples
/// ```ignore
/// // Individual cache:
pub use holon_core::{OperationProvider, OriginTaggedWrites};

/// Observer for operation execution events
///
/// Observers are notified after an operation is successfully executed.
/// This enables cross-cutting concerns like:
/// - Operation logging for undo/redo
/// - Audit trails
/// - Analytics
/// - Sync queue management
///
/// Unlike OperationProvider (which executes operations), observers only
/// observe the results. They cannot modify or veto operations.
///
/// # Entity Filter
/// Observers specify which entities they're interested in via `entity_filter()`:
/// - Return `"*"` to observe all operations (e.g., operation log, audit)
/// - Return a specific entity name to observe only that entity
#[async_trait]
/// flutter_rust_bridge:ignore
pub trait OperationObserver: Send + Sync {
    /// Entity filter for this observer
    ///
    /// Returns `"*"` to observe all entities, or a specific entity name.
    fn entity_filter(&self) -> &str;

    /// Called after an operation is successfully executed
    ///
    /// # Arguments
    /// * `operation` - The operation that was executed
    /// * `undo_action` - The undo action returned by the operation (may be Irreversible)
    ///
    /// # Note
    /// This is called only for successful operations. Failed operations are not observed.
    /// Observers should not perform operations that could fail and block the main flow.
    async fn on_operation_executed(&self, operation: &Operation, undo_action: &UndoAction);
}

// OperationRegistry trait is now defined in holon-core and re-exported above.

/// Trait for persisting and loading sync tokens
///
/// SyncableProviders use this trait to persist their sync tokens across app restarts.
/// Implementations typically store tokens in a database or file system.
/// Trait for storing sync tokens for external providers.
///
/// This trait is used internally for dependency injection and should not be exposed to FFI.
/// flutter_rust_bridge:ignore
#[async_trait]
pub trait SyncTokenStore: Send + Sync {
    /// Load sync token for a provider
    ///
    /// Returns None if no token exists (first sync).
    async fn load_token(&self, provider_name: &str) -> Result<Option<StreamPosition>>;

    /// Save sync token for a provider
    async fn save_token(&self, provider_name: &str, position: StreamPosition) -> Result<()>;

    /// Clear all sync tokens
    ///
    /// Used for full sync operations where all providers need to start from the beginning.
    async fn clear_all_tokens(&self) -> Result<()>;
}

/// Type-independent sync trait for providers
///
/// Providers that can sync from external systems implement this trait.
/// Sync operations are generated dynamically when providers are registered,
/// using the format "{provider_name}.sync" (e.g., "todoist.sync", "jira.sync").
///
/// SyncableProviders should:
/// - Load current token using SyncTokenStore before syncing
/// - Perform sync operation
/// - Save new token using SyncTokenStore after syncing
/// - Return the new token
#[async_trait]
pub trait SyncableProvider: Send + Sync {
    /// Get the provider name (e.g., "todoist", "jira")
    ///
    /// This name is used to generate sync operations and identify the provider.
    fn provider_name(&self) -> &str;

    /// Sync data from the external system
    ///
    /// This method should:
    /// - Load current token using SyncTokenStore
    /// - Fetch updates from the external system using the stream position
    /// - Emit changes via streams (if applicable)
    /// - Save new token using SyncTokenStore
    /// - Return the new stream position
    ///
    /// # Arguments
    /// * `position` - Current stream position (StreamPosition::Beginning for full sync, StreamPosition::Version(token) for incremental sync)
    ///
    /// # Returns
    /// The new stream position (typically StreamPosition::Version with new token, or StreamPosition::Beginning if no token)
    async fn sync(&self, position: StreamPosition) -> Result<StreamPosition>;

    /// Sync pending changes after operation execution.
    ///
    /// Default implementation performs a full sync.
    /// Override for targeted sync (e.g., OrgMode syncs only affected files).
    ///
    /// # Arguments
    /// * `changes` - Field-level changes from the operation
    async fn sync_changes(&self, _: &[FieldDelta]) -> Result<()> {
        self.sync(StreamPosition::Beginning).await?;
        Ok(())
    }
}

/// Trait for external sync providers that emit typed change streams
///
/// This trait allows QueryableCache to register and consume change streams
/// from external systems (Todoist, etc.) in a type-safe way.
/// ExternalServiceDiscovery
pub trait StreamProvider<T>: MaybeSendSync
where
    T: MaybeSendSync + 'static,
{
    /// Get a receiver for changes of type T
    ///
    /// Returns a broadcast receiver that emits batches of changes.
    /// Multiple QueryableCache instances can subscribe to the same stream.
    fn subscribe(&self) -> tokio::sync::broadcast::Receiver<Vec<Change<T>>>;
}

/// Generate a sync operation descriptor for a provider
///
/// This is used by OperationDispatcher when registering SyncableProviders
/// to create operation descriptors with the correct entity_name format.
pub fn generate_sync_operation(provider_name: &str) -> OperationDescriptor {
    OperationDescriptor {
        entity_name: format!("{}.sync", provider_name).into(),
        entity_short_name: "all".to_string(), // Sync operations affect all entities
        id_column: String::new(),             // Sync operations don't need an ID column
        name: "sync".to_string(),
        display_name: format!("Sync {}", provider_name),
        description: format!("Sync data from {} provider", provider_name),
        required_params: vec![],
        affected_fields: vec![], // Sync operations don't affect specific fields
        param_mappings: vec![],
        ..Default::default()
    }
}

/// Trait for operation providers that have a QueryableCache
///
/// This trait provides the `clear_cache` operation that clears all cached data
/// for an entity type. It's used for full sync operations where all cached data
/// should be pruned before re-syncing from the external system.
///
/// The `#[operations_trait]` macro auto-generates the `clear_cache` operation descriptor.
///
/// # Example
/// ```ignore
/// impl HasCache<OrgBlock> for OrgBlockOperations {
///     fn get_cache(&self) -> &QueryableCache<OrgBlock> {
///         &self.cache
///     }
/// }
/// ```
#[holon_macros::operations_trait]
#[async_trait]
pub trait HasCache<T>: MaybeSendSync
where
    T: IntoEntity + TryFromEntity + MaybeSendSync + 'static,
{
    /// Get reference to the underlying QueryableCache
    fn get_cache(&self) -> &QueryableCache<T>;

    /// Clear all cached data for this entity
    ///
    /// This method clears the cache table (DELETE FROM table) and is irreversible.
    /// Used for full sync operations.
    async fn clear_cache(&self) -> Result<UndoAction> {
        self.get_cache().clear().await?;
        Ok(UndoAction::Irreversible)
    }
}
