#!/usr/bin/env bash
set -euo pipefail

# Package a RELEASE-signed Holon APK. Companion to build-apk.sh (the dev/debug
# path); this one never touches the debug keystore. The signing keystore and
# version identity come exclusively from the environment — every variable is
# required and the script fails loud if any is missing.
#
# Required env:
#   KEYSTORE_FILE       path to the release .jks/.keystore
#   KEYSTORE_PASSWORD   keystore (store) password
#   KEY_ALIAS           key alias inside the keystore
#   KEY_PASSWORD        key password
#   VERSION_NAME        e.g. 1.2.0
#   VERSION_CODE        monotonically increasing integer (Play requirement)
# Optional env:
#   ANDROID_SDK_HOME / ANDROID_HOME   SDK root (one must be set)
#   ANDROID_NDK_HOME                  NDK root (defaults to the pinned version)
#
# Prerequisite: the release .so must already exist —
#   cargo ndk -t arm64-v8a -P 33 build -p holon-gpui \
#     --no-default-features --features mobile --lib --release

: "${KEYSTORE_FILE:?KEYSTORE_FILE must point at the release keystore}"
: "${KEYSTORE_PASSWORD:?KEYSTORE_PASSWORD is required}"
: "${KEY_ALIAS:?KEY_ALIAS is required}"
: "${KEY_PASSWORD:?KEY_PASSWORD is required}"
: "${VERSION_NAME:?VERSION_NAME is required (e.g. 1.2.0)}"
: "${VERSION_CODE:?VERSION_CODE is required (integer)}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
# shellcheck source=lib-release-so.sh
source "$SCRIPT_DIR/lib-release-so.sh"

SDK="${ANDROID_SDK_HOME:-${ANDROID_HOME:?ANDROID_SDK_HOME or ANDROID_HOME must be set}}"
BT="$SDK/build-tools/36.0.0"
PLATFORM="$SDK/platforms/android-36/android.jar"
NDK="${ANDROID_NDK_HOME:-$SDK/ndk/29.0.14206865}"
BUILD="$SCRIPT_DIR/build-release"
MANIFEST_SRC="$SCRIPT_DIR/AndroidManifest.xml"

case "$(uname -s)" in
    Darwin) NDK_HOST="darwin-x86_64" ;;
    Linux)  NDK_HOST="linux-x86_64" ;;
    *) echo "ERROR: unsupported host OS: $(uname -s)" >&2; exit 1 ;;
esac
LIBCXX="$NDK/toolchains/llvm/prebuilt/$NDK_HOST/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so"

SO="$PROJECT_ROOT/target/aarch64-linux-android/release/libholon_gpui.so"
for f in "$SO" "$LIBCXX" "$PLATFORM" "$BT/aapt2" "$BT/d8" "$KEYSTORE_FILE"; do
    if [ ! -e "$f" ]; then
        echo "ERROR: required file missing: $f" >&2
        exit 1
    fi
done
command -v javac >/dev/null || { echo "ERROR: javac not on PATH (a JDK is required to build classes.dex)" >&2; exit 1; }

rm -rf "$BUILD"
mkdir -p "$BUILD/lib/arm64-v8a"
stage_release_so "$SO" "$BUILD/lib/arm64-v8a"
cp "$LIBCXX" "$BUILD/lib/arm64-v8a/"

# Compile the vendored soft-keyboard host class (dev.gpui.mobile.GpuiTextInputView)
# to classes.dex. The GPUI Android runtime looks this class up via find_app_class +
# JNI to raise the platform IME, and the manifest declares hasCode="true" — an APK
# without the dex ships a keyboard that can never surface. Small and
# self-contained (imports only android.*) — always rebuilt.
JAVA_SRC="$SCRIPT_DIR/java/dev/gpui/mobile/GpuiTextInputView.java"
mkdir -p "$BUILD/classes" "$BUILD/dex"
javac -source 8 -target 8 -cp "$PLATFORM" -d "$BUILD/classes" "$JAVA_SRC"
"$BT/d8" --min-api 33 --output "$BUILD/dex" "$BUILD/classes"/dev/gpui/mobile/*.class
cp "$BUILD/dex/classes.dex" "$BUILD/classes.dex"

# The checked-in manifest is a dev manifest (android:debuggable="true").
# Google Play rejects debuggable APKs, so strip the attribute for release —
# and fail loud if the manifest shape changed and the strip did nothing.
MANIFEST="$BUILD/AndroidManifest.xml"
sed 's/ android:debuggable="true"//' "$MANIFEST_SRC" > "$MANIFEST"
if grep -q 'debuggable' "$MANIFEST"; then
    echo "ERROR: failed to strip android:debuggable from $MANIFEST_SRC" >&2
    exit 1
fi
if cmp -s "$MANIFEST_SRC" "$MANIFEST"; then
    echo "ERROR: manifest unchanged — expected to strip android:debuggable=\"true\"" >&2
    exit 1
fi

# Compile launcher-icon resources (adaptive mipmaps, generated by
# scripts/export-app-icon.sh into the committed res/ tree) and link them in.
RES_DIR="$PROJECT_ROOT/assets/icons/app/android/res"
[ -d "$RES_DIR" ] || { echo "ERROR: icon res dir missing: $RES_DIR (run scripts/export-app-icon.sh)" >&2; exit 1; }
"$BT/aapt2" compile --dir "$RES_DIR" -o "$BUILD/res.zip"

"$BT/aapt2" link -o "$BUILD/holon-unaligned.apk" \
    --manifest "$MANIFEST" -I "$PLATFORM" \
    --min-sdk-version 33 --target-sdk-version 36 \
    --version-code "$VERSION_CODE" --version-name "$VERSION_NAME" \
    "$BUILD/res.zip"

# classes.dex goes in at APK root, alongside the native libs and BEFORE alignment
# and signing, so the signature covers it.
(cd "$BUILD" && zip -0 holon-unaligned.apk classes.dex lib/arm64-v8a/libholon_gpui.so lib/arm64-v8a/libc++_shared.so)

"$BT/zipalign" -f 4 "$BUILD/holon-unaligned.apk" "$BUILD/holon-release.apk"

# Assert the SHIPPED artifact carries the dex. The manifest declares hasCode="true",
# so an APK without classes.dex installs fine and then fails the runtime
# find_app_class lookup — a defect only reproducible on-device. Checking the aligned
# APK (not the intermediate build dir) is what makes this assertion meaningful.
if ! unzip -Z1 "$BUILD/holon-release.apk" | grep -qxF 'classes.dex'; then
    echo "ERROR: holon-release.apk has no classes.dex — the soft-keyboard host class" >&2
    echo "       (dev.gpui.mobile.GpuiTextInputView) is missing from the shipped APK." >&2
    exit 1
fi

"$BT/apksigner" sign \
    --ks "$KEYSTORE_FILE" \
    --ks-pass "pass:$KEYSTORE_PASSWORD" \
    --ks-key-alias "$KEY_ALIAS" \
    --key-pass "pass:$KEY_PASSWORD" \
    "$BUILD/holon-release.apk"

"$BT/apksigner" verify "$BUILD/holon-release.apk"

echo "Release APK ready: $BUILD/holon-release.apk (versionName=$VERSION_NAME versionCode=$VERSION_CODE)"
