#!/usr/bin/env bash
set -euo pipefail

# Build and optionally install the Holon Android APK.
# Usage: ./build-apk.sh [debug|release] [--install] [--launch]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR/../../.."

# Source .env for build environment
if [ -f "$SCRIPT_DIR/.env" ]; then
    set -a
    source "$SCRIPT_DIR/.env"
    set +a
fi

PROFILE="${1:-release}"
shift || true
INSTALL=false
LAUNCH=false
for arg in "$@"; do
    case "$arg" in
        --install) INSTALL=true ;;
        --launch)  INSTALL=true; LAUNCH=true ;;
    esac
done

SDK="${ANDROID_SDK_HOME:-$HOME/Library/Android/sdk}"
BT="$SDK/build-tools/36.0.0"
PLATFORM="$SDK/platforms/android-36/android.jar"
BUILD="$SCRIPT_DIR/build"
MANIFEST="$SCRIPT_DIR/AndroidManifest.xml"
NDK_VER="29.0.14206865"
NDK="$SDK/ndk/$NDK_VER"

if [ "$PROFILE" = "debug" ]; then
    SO_DIR="$PROJECT_ROOT/target/aarch64-linux-android/debug"
else
    SO_DIR="$PROJECT_ROOT/target/aarch64-linux-android/release"
fi

SO="$SO_DIR/libholon_gpui.so"
if [ ! -f "$SO" ]; then
    echo "ERROR: $SO not found. Run from project root:"
    echo "  cd $PROJECT_ROOT"
    echo "  source frontends/gpui/android/.env"
    echo "  cargo ndk -t arm64-v8a -P 33 build -p holon-gpui --no-default-features --features mobile --lib --release"
    exit 1
fi

echo "Building APK from $SO ($(du -h "$SO" | cut -f1) $(file -b "$SO" | cut -d, -f1-2))"

rm -rf "$BUILD"
mkdir -p "$BUILD/lib/arm64-v8a"

cp "$SO" "$BUILD/lib/arm64-v8a/"
cp "$NDK/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so" \
   "$BUILD/lib/arm64-v8a/"

# Compile the vendored soft-keyboard host class (dev.gpui.mobile.GpuiTextInputView)
# to classes.dex. The GPUI Android runtime looks this class up via find_app_class +
# JNI to raise the platform IME; a pure no-dex NativeActivity APK lacks it entirely,
# so the keyboard can never surface. Small and self-contained — always rebuilt.
JAVA_SRC="$SCRIPT_DIR/java/dev/gpui/mobile/GpuiTextInputView.java"
[ -e "$BT/d8" ] || { echo "ERROR: d8 not found: $BT/d8 (install build-tools;36.0.0)" >&2; exit 1; }
command -v javac >/dev/null || { echo "ERROR: javac not on PATH (a JDK is required to build classes.dex)" >&2; exit 1; }
mkdir -p "$BUILD/classes" "$BUILD/dex"
javac -source 8 -target 8 -cp "$PLATFORM" -d "$BUILD/classes" "$JAVA_SRC"
"$BT/d8" --min-api 33 --output "$BUILD/dex" "$BUILD/classes"/dev/gpui/mobile/*.class
cp "$BUILD/dex/classes.dex" "$BUILD/classes.dex"

# Compile launcher-icon resources (adaptive mipmaps, generated by
# scripts/export-app-icon.sh into the committed res/ tree) and link them in.
RES_DIR="$PROJECT_ROOT/assets/icons/app/android/res"
[ -d "$RES_DIR" ] || { echo "ERROR: icon res dir missing: $RES_DIR (run scripts/export-app-icon.sh)" >&2; exit 1; }
"$BT/aapt2" compile --dir "$RES_DIR" -o "$BUILD/res.zip"

# Link manifest + resources
"$BT/aapt2" link -o "$BUILD/holon-unaligned.apk" \
    --manifest "$MANIFEST" -I "$PLATFORM" \
    --min-sdk-version 33 --target-sdk-version 36 \
    "$BUILD/res.zip"

# Add classes.dex (at APK root) and native libs (stored, not compressed)
cd "$BUILD"
zip -0 holon-unaligned.apk classes.dex lib/arm64-v8a/libholon_gpui.so lib/arm64-v8a/libc++_shared.so
cd "$SCRIPT_DIR"

# Align
"$BT/zipalign" -f 4 "$BUILD/holon-unaligned.apk" "$BUILD/holon.apk"

# Assert the built artifact carries the dex — the manifest declares hasCode="true",
# so without it find_app_class fails at runtime and the keyboard never surfaces.
if ! unzip -Z1 "$BUILD/holon.apk" | grep -qxF 'classes.dex'; then
    echo "ERROR: holon.apk has no classes.dex — the soft-keyboard host class" >&2
    echo "       (dev.gpui.mobile.GpuiTextInputView) is missing from the APK." >&2
    exit 1
fi

# Sign with debug keystore
"$BT/apksigner" sign --ks ~/.android/debug.keystore \
    --ks-pass pass:android --ks-key-alias androiddebugkey \
    "$BUILD/holon.apk"

echo ""
echo "APK ready: $BUILD/holon.apk ($(du -h "$BUILD/holon.apk" | cut -f1))"

if $INSTALL; then
    adb install -r "$BUILD/holon.apk"
fi
if $LAUNCH; then
    adb shell am start -n space.holon.gpui/android.app.NativeActivity
fi

if ! $INSTALL; then
    echo "Install:   adb install -r $BUILD/holon.apk"
    echo "Launch:    adb shell am start -n space.holon.gpui/android.app.NativeActivity"
fi
