#!/usr/bin/env bash
set -euo pipefail

# Package a RELEASE-signed Holon Android App Bundle (.aab). Companion to
# build-release-apk.sh — same keystore, same version identity, same manifest —
# but produces the AAB that Google Play REQUIRES for a new app (APK uploads are
# rejected: "APKs are not allowed for this application"). There is no Gradle
# project; this is a direct aapt2(--proto-format) + bundletool pipeline.
#
# Required env:
#   KEYSTORE_FILE       path to the release .jks/.keystore
#   KEYSTORE_PASSWORD   keystore (store) password
#   KEY_ALIAS           key alias inside the keystore
#   KEY_PASSWORD        key password
#   VERSION_NAME        e.g. 1.2.0
#   VERSION_CODE        monotonically increasing integer (Play requirement)
#   BUNDLETOOL_JAR      path to a bundletool-all-<version>.jar. CI downloads +
#                       checksum-verifies this before calling the script; local
#                       runs point it at a cached copy.
# Optional env:
#   ANDROID_SDK_HOME / ANDROID_HOME   SDK root (one must be set)
#   ANDROID_NDK_HOME                  NDK root (defaults to the pinned version)
#
# Prerequisite: the release .so must already exist —
#   cargo ndk -t arm64-v8a -P 33 build -p holon-gpui \
#     --no-default-features --features mobile --lib --release

: "${KEYSTORE_FILE:?KEYSTORE_FILE must point at the release keystore}"
: "${KEYSTORE_PASSWORD:?KEYSTORE_PASSWORD is required}"
: "${KEY_ALIAS:?KEY_ALIAS is required}"
: "${KEY_PASSWORD:?KEY_PASSWORD is required}"
: "${VERSION_NAME:?VERSION_NAME is required (e.g. 1.2.0)}"
: "${VERSION_CODE:?VERSION_CODE is required (integer)}"
: "${BUNDLETOOL_JAR:?BUNDLETOOL_JAR must point at a bundletool-all-<version>.jar}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR/../../.."
# shellcheck source=lib-release-so.sh
source "$SCRIPT_DIR/lib-release-so.sh"

SDK="${ANDROID_SDK_HOME:-${ANDROID_HOME:?ANDROID_SDK_HOME or ANDROID_HOME must be set}}"
BT="$SDK/build-tools/36.0.0"
PLATFORM="$SDK/platforms/android-36/android.jar"
NDK="${ANDROID_NDK_HOME:-$SDK/ndk/29.0.14206865}"
BUILD="$SCRIPT_DIR/build-release-aab"
MANIFEST_SRC="$SCRIPT_DIR/AndroidManifest.xml"

case "$(uname -s)" in
    Darwin) NDK_HOST="darwin-x86_64" ;;
    Linux)  NDK_HOST="linux-x86_64" ;;
    *) echo "ERROR: unsupported host OS: $(uname -s)" >&2; exit 1 ;;
esac
LIBCXX="$NDK/toolchains/llvm/prebuilt/$NDK_HOST/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so"

SO="$PROJECT_ROOT/target/aarch64-linux-android/release/libholon_gpui.so"
for f in "$SO" "$LIBCXX" "$PLATFORM" "$BT/aapt2" "$BT/d8" "$KEYSTORE_FILE" "$BUNDLETOOL_JAR"; do
    if [ ! -e "$f" ]; then
        echo "ERROR: required file missing: $f" >&2
        exit 1
    fi
done
command -v javac >/dev/null || { echo "ERROR: javac not on PATH (a JDK is required to build classes.dex)" >&2; exit 1; }

rm -rf "$BUILD"
mkdir -p "$BUILD/module/lib/arm64-v8a" "$BUILD/module/manifest" "$BUILD/module/dex" \
    "$BUILD/classes" "$BUILD/dex" "$BUILD/proto"
stage_release_so "$SO" "$BUILD/module/lib/arm64-v8a"
cp "$LIBCXX" "$BUILD/module/lib/arm64-v8a/"

# Compile the vendored soft-keyboard host class (dev.gpui.mobile.GpuiTextInputView)
# to classes.dex. This app is NO LONGER a pure no-dex NativeActivity: the GPUI
# runtime looks this class up via find_app_class + JNI to raise the platform IME,
# so the dex is REQUIRED in the base module (manifest hasCode="true"). Small and
# self-contained (imports only android.*) — always rebuilt.
JAVA_SRCS=(
    "$SCRIPT_DIR/java/dev/gpui/mobile/GpuiTextInputView.java"
    "$SCRIPT_DIR/java/dev/gpui/mobile/GpuiNativeActivity.java"
)
javac -source 8 -target 8 -cp "$PLATFORM" -d "$BUILD/classes" "${JAVA_SRCS[@]}"
"$SCRIPT_DIR/check-natives.sh" "$BUILD/classes" "$SO" \
    "$NDK/toolchains/llvm/prebuilt/$NDK_HOST/bin/llvm-nm"
"$BT/d8" --min-api 33 --output "$BUILD/dex" "$BUILD/classes"/dev/gpui/mobile/*.class
# bundletool base-module layout carries dex under dex/ (peer of manifest/, lib/).
cp "$BUILD/dex/classes.dex" "$BUILD/module/dex/classes.dex"

# The checked-in manifest is a dev manifest (android:debuggable="true").
# Google Play rejects debuggable builds, so strip the attribute for release —
# and fail loud if the manifest shape changed and the strip did nothing.
MANIFEST="$BUILD/AndroidManifest.xml"
sed 's/ android:debuggable="true"//' "$MANIFEST_SRC" > "$MANIFEST"
if grep -q 'debuggable' "$MANIFEST"; then
    echo "ERROR: failed to strip android:debuggable from $MANIFEST_SRC" >&2
    exit 1
fi
if cmp -s "$MANIFEST_SRC" "$MANIFEST"; then
    echo "ERROR: manifest unchanged — expected to strip android:debuggable=\"true\"" >&2
    exit 1
fi

# Compile launcher-icon resources (adaptive mipmaps, generated by
# scripts/export-app-icon.sh into the committed res/ tree) — the same input the
# APK scripts compile. The manifest references @mipmap/ic_launcher{,_round}, so
# without these the link below cannot resolve them.
RES_DIR="$PROJECT_ROOT/assets/icons/app/android/res"
[ -d "$RES_DIR" ] || { echo "ERROR: icon res dir missing: $RES_DIR (run scripts/export-app-icon.sh)" >&2; exit 1; }
"$BT/aapt2" compile --dir "$RES_DIR" -o "$BUILD/res.zip"

# 1. Link manifest + compiled resources into a PROTOBUF-format APK. bundletool
#    consumes proto, not the binary AXML the APK pipeline uses.
"$BT/aapt2" link --proto-format -o "$BUILD/base-proto.apk" \
    --manifest "$MANIFEST" -I "$PLATFORM" \
    --min-sdk-version 33 --target-sdk-version 36 \
    --version-code "$VERSION_CODE" --version-name "$VERSION_NAME" \
    "$BUILD/res.zip"

# 2. Unpack the proto APK → proto AndroidManifest.xml + resources.pb + res/.
unzip -o -q "$BUILD/base-proto.apk" -d "$BUILD/proto"
for f in AndroidManifest.xml resources.pb res; do
    if [ ! -e "$BUILD/proto/$f" ]; then
        echo "ERROR: aapt2 --proto-format did not emit $f" >&2
        exit 1
    fi
done

# 3. Assemble the base module in bundletool's expected layout:
#      manifest/AndroidManifest.xml   (proto)
#      dex/classes.dex                (the soft-keyboard host class)
#      resources.pb                   (resource table, incl. the mipmap entries)
#      res/mipmap-*/…                 (the launcher-icon files resources.pb points at)
#      lib/arm64-v8a/*.so
#    resources.pb without res/ is a dangling table: the icon ids resolve to file
#    paths that are not in the bundle. Both halves ship, and both are asserted
#    below — as is the dex, which the manifest's hasCode="true" requires.
cp "$BUILD/proto/AndroidManifest.xml" "$BUILD/module/manifest/AndroidManifest.xml"
cp "$BUILD/proto/resources.pb" "$BUILD/module/resources.pb"
cp -R "$BUILD/proto/res" "$BUILD/module/res"
(cd "$BUILD/module" && zip -q -r -X "../base.zip" manifest dex resources.pb res lib)

# 4. Build the bundle.
java -jar "$BUNDLETOOL_JAR" build-bundle \
    --modules="$BUILD/base.zip" \
    --output="$BUILD/holon-release.aab"

# Assert the SHIPPED bundle carries the dex. The manifest declares hasCode="true",
# so a bundle without it installs fine and then fails the runtime find_app_class
# lookup — a defect only reproducible on-device. Checking the .aab itself (not the
# staging dir bundletool consumed) is what makes this assertion meaningful.
# No `grep -q` here: its early exit SIGPIPEs unzip, which `pipefail` then reports
# as a missing dex.
if ! unzip -Z1 "$BUILD/holon-release.aab" | grep 'dex/classes\.dex$' >/dev/null; then
    echo "ERROR: holon-release.aab has no dex/classes.dex — the soft-keyboard host" >&2
    echo "       class (dev.gpui.mobile.GpuiTextInputView) is missing from the bundle." >&2
    exit 1
fi

# Assert the SHIPPED bundle carries the launcher icons the manifest references
# (@mipmap/ic_launcher, @mipmap/ic_launcher_round). A bundle whose res/ never
# made it past the module zip installs with a blank system-default icon —
# invisible to every check that stops at the intermediates.
MIPMAPS="$(unzip -Z1 "$BUILD/holon-release.aab" | grep -c 'res/mipmap[^/]*/ic_launcher' || true)"
if [ "$MIPMAPS" -lt 2 ]; then
    echo "ERROR: holon-release.aab carries $MIPMAPS res/mipmap ic_launcher entries (expected at" >&2
    echo "       least 2) — the manifest's @mipmap/ic_launcher{,_round} would resolve" >&2
    echo "       to files absent from the bundle and the app would ship icon-less." >&2
    exit 1
fi

# 5. Sign the AAB with jarsigner (Play's requirement for uploaded bundles),
#    using the SAME keystore/env as the APK's apksigner step. Passwords are
#    passed via :env so they never appear in the process list or logs.
jarsigner -keystore "$KEYSTORE_FILE" \
    -storepass:env KEYSTORE_PASSWORD \
    -keypass:env KEY_PASSWORD \
    -sigalg SHA256withRSA -digestalg SHA-256 \
    "$BUILD/holon-release.aab" "$KEY_ALIAS"

jarsigner -verify "$BUILD/holon-release.aab"

# 6. Structural validation.
java -jar "$BUNDLETOOL_JAR" validate --bundle="$BUILD/holon-release.aab"

echo "Release AAB ready: $BUILD/holon-release.aab (versionName=$VERSION_NAME versionCode=$VERSION_CODE)"
