[package]
name = "holon-profiles"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow.workspace = true
futures.workspace = true
futures-signals.workspace = true
holon-api.workspace = true
holon-core.workspace = true
holon-engine.workspace = true
holon-macros.workspace = true
rhai.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tokio = { workspace = true, features = ["rt"] }
tracing.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
