//! Render DSL: Rhai-based language for defining render expressions.
//!
//! Render source blocks contain Rhai expressions that produce a render tree.
//! Each widget function (columns, list, tree, text, icon, etc.) is registered
//! as a Rhai function that returns a Dynamic map describing a RenderExpr node.
//!
//! ## Widget registry seam
//!
//! Adding a new widget like `kanban`, `calendar`, or a parametric-style function
//! does **not** require touching the `RenderExpr` enum or this parser. The seam:
//!
//! 1. Parse-time: every identifier-followed-by-`(` in the source is treated as a
//!    widget call. The parser scans the source for such names and registers them
//!    with Rhai automatically. New names need no explicit registration.
//! 2. Interpret-time: the frontend's shadow builder registry (auto-generated by
//!    `holon_macros::builder_registry!`) resolves the widget name to a builder.
//!    A new widget appears by adding a builder file under
//!    `crates/holon-frontend/src/shadow_builders/`.
//!
//! `register_widget_names` is an *optional* hint used by the frontend to seed the
//! engine with the canonical set up-front. The parser falls back to source-driven
//! discovery when names aren't pre-registered (tests, headless backend code).
//!
//! ## Syntax examples
//!
//! ```rhai
//! columns(#{gap: 4, item_template: live_block()})
//!
//! list(#{sortkey: "name", item_template: render_entity()})
//!
//! tree(#{parent_id: col("parent_id"), sortkey: col("id"), item_template: render_entity()})
//!
//! list(#{item_template: selectable(
//!     row(icon("folder"), spacer(6), text(col("name"))),
//!     #{action: navigation_focus(#{region: "main", block_id: col("doc_uri")})}
//! )})
//! ```
//!
//! ## Special functions
//!
//! - `col("name")` — column reference (resolved per-row at render time)
//! - All other functions map to RenderExpr::FunctionCall nodes

use std::collections::HashMap;
use std::sync::OnceLock;

use anyhow::{Context, Result};
use holon_api::Value;
use holon_api::render_types::{Arg, RenderExpr};
use rhai::{Dynamic, Engine as RhaiEngine, Map as RhaiMap};

/// Global widget name registry. **Optional hint** populated by the frontend at
/// startup via `register_widget_names()`. Callers that don't reach the
/// frontend (backend tests, headless engines, action_watcher) get the same
/// behavior because `parse_render_dsl()` also scans the source for any
/// identifier-in-call-position and registers it ad hoc.
static WIDGET_NAMES: OnceLock<Vec<String>> = OnceLock::new();

/// Pre-register the canonical widget name list with the parser (optional hint).
///
/// Called at startup by the frontend, passing the auto-generated
/// `builder_names()` from the shadow builder registry. Subsequent calls are
/// ignored (OnceLock semantics). When this isn't called (tests, backend-only
/// code), `parse_render_dsl()` discovers names from the source itself.
pub fn register_widget_names(names: &[&str]) {
    let _ = WIDGET_NAMES.set(names.iter().map(|s| s.to_string()).collect());
}

/// Get the pre-registered widget names. Returns `&[]` if `register_widget_names`
/// was never called — callers must combine with `extract_function_names(source)`
/// before parsing, which `parse_render_dsl()` does automatically.
pub fn registered_widget_names() -> &'static [String] {
    static EMPTY: Vec<String> = Vec::new();
    WIDGET_NAMES.get().unwrap_or(&EMPTY)
}

/// Parse a render DSL string into a RenderExpr.
///
/// Discovers widget names by union of:
/// (a) names pre-registered via `register_widget_names()` (frontend startup), and
/// (b) identifier-in-call-position tokens scanned from `source` itself.
///
/// The second source means new widgets like `kanban(#{...})` parse without any
/// registration — the frontend needs to add the builder, but the parser is
/// extension-free.
pub fn parse_render_dsl(source: &str) -> Result<RenderExpr> {
    let mut names: Vec<String> = registered_widget_names().to_vec();
    for name in extract_function_names(source) {
        if !names.iter().any(|n| n == &name) {
            names.push(name);
        }
    }
    let name_refs: Vec<&str> = names.iter().map(String::as_str).collect();
    parse_render_dsl_with_engine(source, &create_render_engine_with_names(&name_refs))
}

/// Parse a render DSL string using an explicit set of widget names.
///
/// Used by the frontend's `RenderInterpreter::parse_dsl` which already has the
/// builder registry on hand. Source-extracted names are still unioned in so
/// new widgets in the source parse without an explicit registry update.
pub fn parse_render_dsl_with_names(source: &str, names: &[&str]) -> Result<RenderExpr> {
    let mut all: Vec<String> = names.iter().map(|s| (*s).to_string()).collect();
    for name in extract_function_names(source) {
        if !all.iter().any(|n| n == &name) {
            all.push(name);
        }
    }
    let name_refs: Vec<&str> = all.iter().map(String::as_str).collect();
    parse_render_dsl_with_engine(source, &create_render_engine_with_names(&name_refs))
}

/// Rhai keywords / built-ins that must NOT be registered as widget functions.
/// Registering these would either fail or shadow language constructs.
const RHAI_RESERVED: &[&str] = &[
    "if", "else", "for", "in", "while", "do", "loop", "until", "break", "continue", "return", "fn",
    "let", "const", "private", "true", "false", "null", "switch", "try", "catch", "throw",
    "import", "export", "as", "is", "this",
];

/// Scan a Rhai source for identifiers in function-call position (`name(`).
///
/// Skips string literals (single/double quoted) and `//` line comments so
/// occurrences inside `text("foo(bar)")` don't false-positive. Filters out
/// Rhai reserved words. Used by `parse_render_dsl` to bootstrap the engine
/// with widget functions for any name the source mentions, eliminating the
/// need to update a global registry when adding a new widget.
fn extract_function_names(source: &str) -> Vec<String> {
    let bytes = source.as_bytes();
    let mut names: Vec<String> = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i];
        // Skip string literals
        if c == b'"' || c == b'\'' {
            let quote = c;
            i += 1;
            while i < bytes.len() && bytes[i] != quote {
                if bytes[i] == b'\\' && i + 1 < bytes.len() {
                    i += 2;
                } else {
                    i += 1;
                }
            }
            if i < bytes.len() {
                i += 1;
            }
            continue;
        }
        // Skip `//` line comments
        if c == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        // Identifier start: letter or underscore
        if c == b'_' || c.is_ascii_alphabetic() {
            let start = i;
            while i < bytes.len() && (bytes[i] == b'_' || bytes[i].is_ascii_alphanumeric()) {
                i += 1;
            }
            let id_end = i;
            // Skip whitespace between identifier and `(`
            while i < bytes.len() && bytes[i].is_ascii_whitespace() {
                i += 1;
            }
            if i < bytes.len() && bytes[i] == b'(' {
                let name = &source[start..id_end];
                if !RHAI_RESERVED.contains(&name) && !names.iter().any(|n| n == name) {
                    names.push(name.to_string());
                }
            }
            continue;
        }
        i += 1;
    }
    names
}

fn parse_render_dsl_with_engine(source: &str, engine: &RhaiEngine) -> Result<RenderExpr> {
    let trimmed = source.trim();
    if trimmed.is_empty() {
        return Ok(default_table());
    }

    // Try JSON first (backwards compat)
    if let Ok(expr) = serde_json::from_str::<RenderExpr>(trimmed) {
        return Ok(expr);
    }

    let result = engine
        .eval_expression::<Dynamic>(trimmed)
        .map_err(|e| anyhow::anyhow!("Failed to parse render DSL '{}': {e}", trimmed))?;

    dynamic_to_render_expr(&result)
        .with_context(|| format!("Failed to convert Rhai result to RenderExpr: {:?}", &result))
}

fn default_table() -> RenderExpr {
    RenderExpr::FunctionCall {
        name: "table".to_string(),
        args: Vec::new(),
    }
}

/// Create a Rhai engine with all render functions registered.
///
/// Widget names come from `registered_widget_names()` (the optional frontend
/// hint set via `register_widget_names()`). When no names are pre-registered
/// the engine carries only `col(...)`; callers that need to evaluate widget
/// calls should prefer `parse_render_dsl()` (which adds source-extracted
/// names) or `create_render_engine_with_names()` with an explicit list.
pub fn create_render_engine() -> RhaiEngine {
    create_render_engine_with_names(registered_widget_names())
}

/// Create a Rhai engine with an explicit set of widget names.
pub fn create_render_engine_with_names(widget_names: &[impl AsRef<str>]) -> RhaiEngine {
    let mut engine = RhaiEngine::new();

    // col("name") → ColumnRef marker
    engine.register_fn("col", |name: &str| -> Dynamic {
        let mut map = RhaiMap::new();
        map.insert("_type".into(), "col".into());
        map.insert("name".into(), Dynamic::from(name.to_string()));
        Dynamic::from(map)
    });

    for name in widget_names {
        register_widget_fn(&mut engine, name.as_ref());
    }

    // Dotted names: Rhai doesn't allow dots in function names,
    // so users write underscores and we map to the dotted name.
    register_widget_fn_aliased(&mut engine, "navigation_focus", "navigation.focus");

    engine
}

/// Register a widget function where the Rhai name differs from the output name.
/// E.g., `navigation_focus` in Rhai → `navigation.focus` in RenderExpr.
fn register_widget_fn_aliased(engine: &mut RhaiEngine, rhai_name: &str, output_name: &str) {
    let n = output_name.to_string();

    let n0 = n.clone();
    engine.register_fn(rhai_name, move || -> Dynamic { make_fn_node(&n0, vec![]) });
    let n1 = n.clone();
    engine.register_fn(rhai_name, move |a: Dynamic| -> Dynamic {
        make_fn_node(&n1, vec![a])
    });
    let n2 = n.clone();
    engine.register_fn(rhai_name, move |a: Dynamic, b: Dynamic| -> Dynamic {
        make_fn_node(&n2, vec![a, b])
    });
    let n3 = n.clone();
    engine.register_fn(
        rhai_name,
        move |a: Dynamic, b: Dynamic, c: Dynamic| -> Dynamic { make_fn_node(&n3, vec![a, b, c]) },
    );
}

fn register_widget_fn(engine: &mut RhaiEngine, name: &str) {
    let n = name.to_string();

    // 0-arg: live_block()
    let n0 = n.clone();
    engine.register_fn(name, move || -> Dynamic { make_fn_node(&n0, vec![]) });

    // 1-arg: columns(#{gap: 4}) or text("hello") or text(col("name"))
    let n1 = n.clone();
    engine.register_fn(name, move |arg: Dynamic| -> Dynamic {
        make_fn_node(&n1, vec![arg])
    });

    // 2-arg: selectable(child, #{action: ...})
    let n2 = n.clone();
    engine.register_fn(name, move |a: Dynamic, b: Dynamic| -> Dynamic {
        make_fn_node(&n2, vec![a, b])
    });

    // 3-arg: row(a, b, c)
    let n3 = n.clone();
    engine.register_fn(name, move |a: Dynamic, b: Dynamic, c: Dynamic| -> Dynamic {
        make_fn_node(&n3, vec![a, b, c])
    });

    // 4-arg
    let n4 = n.clone();
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic| -> Dynamic {
            make_fn_node(&n4, vec![a, b, c, d])
        },
    );

    // 5-arg
    let n5 = n.clone();
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic, e: Dynamic| -> Dynamic {
            make_fn_node(&n5, vec![a, b, c, d, e])
        },
    );

    // 6-arg
    let n6 = n.clone();
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic, e: Dynamic, f: Dynamic| -> Dynamic {
            make_fn_node(&n6, vec![a, b, c, d, e, f])
        },
    );
}

/// Build a function node Dynamic.
///
/// Convention: the LAST Map argument is treated as named args.
/// All other arguments are positional.
fn make_fn_node(name: &str, args: Vec<Dynamic>) -> Dynamic {
    let mut map = RhaiMap::new();
    map.insert("_type".into(), "fn".into());
    map.insert("_name".into(), Dynamic::from(name.to_string()));

    let mut positional = Vec::new();
    let mut named = RhaiMap::new();

    for arg in args.into_iter() {
        if arg.is_map() {
            // Check if it's a col() marker or a fn node — those are positional
            let m = arg.clone().cast::<RhaiMap>();
            if m.contains_key("_type") {
                positional.push(arg);
            } else {
                // Plain map = named args (merge into named)
                for (k, v) in m {
                    named.insert(k, v);
                }
            }
        } else {
            positional.push(arg);
        }
    }

    map.insert("_positional".into(), Dynamic::from(positional));
    map.insert("_named".into(), Dynamic::from(named));
    Dynamic::from(map)
}

// ---------------------------------------------------------------------------
// Dynamic → RenderExpr conversion
// ---------------------------------------------------------------------------

pub fn dynamic_to_render_expr(d: &Dynamic) -> Result<RenderExpr> {
    if d.is_map() {
        let map = d.clone().cast::<RhaiMap>();

        let typ = map
            .get("_type")
            .and_then(|v| v.clone().into_string().ok()) // ALLOW(ok): non-string → None
            .unwrap_or_default();

        match typ.as_str() {
            "fn" => map_to_function_call(&map),
            "col" => {
                let name = map
                    .get("name")
                    .and_then(|v| v.clone().into_string().ok()) // ALLOW(ok): non-string → None
                    .unwrap_or_default();
                Ok(RenderExpr::ColumnRef { name })
            }
            _ => {
                // Plain map without _type — treat as Object
                let mut fields = HashMap::new();
                for (k, v) in &map {
                    fields.insert(k.to_string(), dynamic_to_render_expr(v)?);
                }
                Ok(RenderExpr::Object { fields })
            }
        }
    } else if d.is_array() {
        let arr = d.clone().cast::<Vec<Dynamic>>();
        let items: Result<Vec<_>> = arr.iter().map(dynamic_to_render_expr).collect();
        Ok(RenderExpr::Array { items: items? })
    } else {
        // Primitive → Literal
        Ok(RenderExpr::Literal {
            value: dynamic_to_value(d),
        })
    }
}

fn map_to_function_call(map: &RhaiMap) -> Result<RenderExpr> {
    let name = map
        .get("_name")
        .and_then(|v| v.clone().into_string().ok()) // ALLOW(ok): non-string → None
        .unwrap_or_else(|| "unknown".to_string());

    let mut args = Vec::new();

    // Named args
    if let Some(named_dyn) = map.get("_named") {
        if named_dyn.is_map() {
            let named = named_dyn.clone().cast::<RhaiMap>();
            for (k, v) in &named {
                args.push(Arg {
                    name: Some(k.to_string()),
                    value: dynamic_to_render_expr(v)?,
                });
            }
        }
    }

    // Positional args
    if let Some(pos_dyn) = map.get("_positional") {
        if pos_dyn.is_array() {
            let positional = pos_dyn.clone().cast::<Vec<Dynamic>>();
            for v in &positional {
                args.push(Arg {
                    name: None,
                    value: dynamic_to_render_expr(v)?,
                });
            }
        }
    }

    Ok(RenderExpr::FunctionCall { name, args })
}

fn dynamic_to_value(d: &Dynamic) -> Value {
    if d.is_int() {
        Value::Integer(d.as_int().unwrap())
    } else if d.is_float() {
        Value::Float(d.as_float().unwrap())
    } else if d.is_bool() {
        Value::Boolean(d.as_bool().unwrap())
    } else if d.is_string() {
        Value::String(d.clone().into_string().unwrap())
    } else if d.is_unit() {
        Value::Null
    } else {
        Value::String(format!("{d:?}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(source: &str) -> Result<RenderExpr> {
        register_widget_names(&[
            "table",
            "live_block",
            "columns",
            "text",
            "row",
            "icon",
            "spacer",
            "tree",
            "render_entity",
            "list",
            "selectable",
            "chain_ops",
        ]);
        parse_render_dsl(source)
    }

    #[test]
    fn test_simple_function() {
        let expr = parse("table()").unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));
    }

    #[test]
    fn test_live_block() {
        let expr = parse("live_block()").unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "live_block"));
    }

    #[test]
    fn test_columns_with_named_args() {
        let expr = parse("columns(#{gap: 4, item_template: live_block()})").unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "columns");
            assert!(args.iter().any(|a| a.name.as_deref() == Some("gap")));
            assert!(
                args.iter()
                    .any(|a| a.name.as_deref() == Some("item_template"))
            );
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_col_reference() {
        let expr = parse("text(col(\"name\"))").unwrap();
        if let RenderExpr::FunctionCall { args, .. } = &expr {
            assert!(matches!(&args[0].value, RenderExpr::ColumnRef { name } if name == "name"));
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_nested_functions() {
        let expr =
            parse_render_dsl(r#"row(icon("folder"), spacer(6), text(col("name")))"#).unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "row");
            assert_eq!(args.len(), 3);
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_tree_with_col_refs() {
        let expr = parse(r#"tree(#{parent_id: col("parent_id"), sortkey: col("id"), item_template: render_entity()})"#).unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "tree");
            let parent_arg = args
                .iter()
                .find(|a| a.name.as_deref() == Some("parent_id"))
                .unwrap();
            assert!(
                matches!(&parent_arg.value, RenderExpr::ColumnRef { name } if name == "parent_id")
            );
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_json_backwards_compat() {
        // Old JSON with operations field should still parse (serde ignores unknown fields)
        let json = r#"{"FunctionCall":{"name":"table","args":[],"operations":[]}}"#;
        let expr = parse(json).unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));

        let json = r#"{"FunctionCall":{"name":"table","args":[]}}"#;
        let expr = parse(json).unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));
    }

    #[test]
    fn test_empty_defaults_to_table() {
        let expr = parse("").unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));
    }

    #[test]
    fn test_widget_with_integer_arg() {
        let expr = parse("chain_ops(0)").unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "chain_ops");
            assert_eq!(args.len(), 1);
        } else {
            panic!("Expected FunctionCall");
        }
    }

    /// Phase 2 exit criteria: a brand-new widget name parses without enum,
    /// parser, or registry change. The frontend just needs to add a builder
    /// for it — the parse path is extension-free.
    #[test]
    fn new_widget_parses_without_explicit_registration() {
        // Use parse_render_dsl directly with no register_widget_names call —
        // the source-driven discovery path must handle this on its own.
        let expr = parse_render_dsl(
            r#"kanban(#{group_by: "task_state", item_template: render_entity()})"#,
        )
        .unwrap();
        match expr {
            RenderExpr::FunctionCall { name, args } => {
                assert_eq!(name, "kanban");
                assert!(args.iter().any(|a| a.name.as_deref() == Some("group_by")));
                assert!(
                    args.iter()
                        .any(|a| a.name.as_deref() == Some("item_template"))
                );
            }
            other => panic!("Expected FunctionCall(kanban), got {other:?}"),
        }
    }

    #[test]
    fn nested_new_widgets_parse_without_registration() {
        let expr = parse_render_dsl(
            r#"calendar(#{view: "month", item_template: holiday_badge(text(col("title")))})"#,
        )
        .unwrap();
        if let RenderExpr::FunctionCall { name, args } = &expr {
            assert_eq!(name, "calendar");
            // The nested holiday_badge widget should have parsed too.
            let item_template = args
                .iter()
                .find(|a| a.name.as_deref() == Some("item_template"))
                .expect("calendar has item_template");
            assert!(matches!(
                &item_template.value,
                RenderExpr::FunctionCall { name, .. } if name == "holiday_badge"
            ));
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn extract_function_names_skips_string_literals_and_comments() {
        let source = r#"row(text("foo(bar)"), icon("baz")) // not_a_widget(blah)"#;
        let names = extract_function_names(source);
        assert!(names.contains(&"row".to_string()));
        assert!(names.contains(&"text".to_string()));
        assert!(names.contains(&"icon".to_string()));
        assert!(
            !names.contains(&"foo".to_string()),
            "string-literal contents must not register"
        );
        assert!(
            !names.contains(&"bar".to_string()),
            "string-literal contents must not register"
        );
        assert!(
            !names.contains(&"not_a_widget".to_string()),
            "comment contents must not register"
        );
    }

    #[test]
    fn extract_function_names_skips_rhai_keywords() {
        // `if` and `let` would happen to look like fn calls if they appeared
        // before `(` in the source — make sure they never get registered.
        let names = extract_function_names("if (x > 0) { table() }");
        assert!(!names.contains(&"if".to_string()));
        assert!(names.contains(&"table".to_string()));
    }
}
