[package]
name = "holon-orgmode-testing"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "holon_orgmode_testing"
path = "src/lib.rs"

[dependencies]
holon-api = { workspace = true }
holon-orgmode = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
