//! Block round-trip PBT through the **Org format adapter**.
//!
//! Sister test to `turso_block_round_trip_pbt.rs` (in the `holon` crate).
//! Both PBTs use the same generators + assertion from
//! `holon-block-roundtrip-testing`; each test owns its own write/read pair.
//!
//! Direction tested here:
//! ```text
//! Vec<Block> --[OrgFormatAdapter::render_document]--> file bytes
//!            <--[OrgFormatAdapter::parse]------------ file bytes
//! assert_normalized_docs_equal(generated, parsed)
//! ```
//!
//! This is an explicit, small regression gate for the headline-tag drop bug
//! (May 2026) — generated `:edge_abstraction:` style tags must survive the
//! adapter round-trip. The pre-existing `round_trip_pbt::test_round_trip`
//! continues to do the heavyweight per-format checks (sequence ordering,
//! mutations, etc.); this PBT just exercises the shared property through
//! the public adapter surface so the same shape can be replicated for
//! Turso, Markdown, and any future format crate.
//!
//! Headlines generated by the shared `headline_spec_strategy` use only TODO
//! keywords that fall within the parser defaults (`TODO`, `DOING`, `DONE`,
//! `CANCELLED`, `CLOSED`), so the generated document never needs an explicit
//! `#+TODO:` header for round-trip parity.

use std::path::PathBuf;

use holon_api::block::Block;
use holon_api::entity_uri::EntityUri;
use holon_block_roundtrip_testing::NormalizedDocument;
use holon_block_roundtrip_testing::assert_normalized_docs_equal;
use holon_block_roundtrip_testing::build_blocks;
use holon_block_roundtrip_testing::root_headlines_strategy;
use holon_block_roundtrip_testing::valid_title;
use holon_core::file_format::FileFormatAdapter;
use holon_orgmode::file_format::OrgFormatAdapter;
use holon_orgmode::models::OrgDocumentExt;
use proptest::prelude::*;
use uuid::Uuid;

fn doc_strategy() -> impl Strategy<Value = Block> {
    prop::option::of(valid_title()).prop_map(|title| {
        let id = EntityUri::block(&format!("test-{}", Uuid::new_v4()));
        let mut doc = Block::new_text(id, EntityUri::no_parent(), "test.org");
        doc.set_page(true);
        doc.set_file_title(title);
        // No explicit todo_keywords — headlines use parser defaults.
        doc.set_todo_keywords(None);
        doc
    })
}

proptest! {
    // T1 PBT (Phase 4 of the testing-strategy plan). Runtime measured at
    // ~0.3s for 50 cases; 1024 cases finish well under the <30s T1 budget
    // and exercise the generator surface far more thoroughly than the
    // legacy 50-case settings. Failure seeds land in `proptest-regressions/`
    // via proptest's default `FileFailurePersistence::SourceParallel`.
    #![proptest_config(ProptestConfig {
        cases: 1024,
        failure_persistence: None,
        ..ProptestConfig::default()
    })]

    #[test]
    fn block_round_trips_through_org_adapter(
        doc in doc_strategy(),
        headlines in root_headlines_strategy(),
    ) {
        let adapter = OrgFormatAdapter::new();
        let blocks = build_blocks(&doc.id, &headlines);

        let path = PathBuf::from("/test/test.org");
        let root = PathBuf::from("/test");

        let org_text = adapter.render_document(&doc, &blocks, &path, &doc.id);

        let parsed = adapter
            .parse(&path, &org_text, &EntityUri::no_parent(), &root)
            .map_err(|e| {
                TestCaseError::fail(format!("parse failed: {e}\n\norg text:\n{org_text}"))
            })?;

        let expected = NormalizedDocument::from_blocks(doc.file_title(), &blocks);
        let actual =
            NormalizedDocument::from_blocks(parsed.document.file_title(), &parsed.blocks);

        assert_normalized_docs_equal(&expected, &actual, "org_round_trip")?;
    }
}
