#!/usr/bin/env python3
"""Query and index the bug funnel.

The funnel is one file per escape under `docs/Testing/bugfunnel/entries/`.
Totals are derived here and never stored, so two lanes adding an escape can
never disagree about a counter.

  bugfunnel.py counts                 gap distribution (the old header line)
  bugfunnel.py list --status OPEN     one line per matching escape
  bugfunnel.py index                  regenerate INDEX.md
  bugfunnel.py check                  validate every entry against the schema
"""

import argparse
import re
import sys
from pathlib import Path

import yaml

GAPS = ("ENVIRONMENT", "COVERAGE", "PERCEPTION", "ORACLE")
STATUSES = ("FIXED", "PARTIAL", "MITIGATED", "OPEN", "NOTED", "UNCLASSIFIED")
FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
REQUIRED = ("id", "date", "gap", "status", "summary")


def load(entries_dir):
    entries = []
    problems = []
    for path in sorted(entries_dir.glob("*.md")):
        text = path.read_text()
        match = FRONTMATTER_RE.match(text)
        if not match:
            problems.append(f"{path.name}: no YAML frontmatter")
            continue
        meta = yaml.safe_load(match.group(1))
        for key in REQUIRED:
            if meta.get(key) in (None, ""):
                problems.append(f"{path.name}: missing `{key}`")
        if meta.get("gap") not in GAPS:
            problems.append(f"{path.name}: gap {meta.get('gap')!r} is not one of {GAPS}")
        if meta.get("status") not in STATUSES:
            problems.append(f"{path.name}: status {meta.get('status')!r} is not one of {STATUSES}")
        if meta.get("id") != path.stem:
            problems.append(f"{path.name}: id {meta.get('id')!r} does not match the filename")
        meta["path"] = path
        entries.append(meta)
    return entries, problems


def select(entries, args):
    out = entries
    if args.gap:
        out = [e for e in out if e["gap"] == args.gap or e.get("secondary") == args.gap]
    if args.status:
        out = [e for e in out if e["status"] == args.status]
    if args.since:
        out = [e for e in out if str(e["date"]) >= args.since]
    return sorted(out, key=lambda e: (str(e["date"]), e["id"]), reverse=True)


def one_line(entry, limit=None):
    summary = " ".join(str(entry["summary"]).split())
    if limit and len(summary) > limit:
        summary = summary[:limit].rsplit(" ", 1)[0] + "…"
    secondary = f"/{entry['secondary']}" if entry.get("secondary") else ""
    return f"{entry['date']} {entry['gap']}{secondary} {entry['status']} {entry['id']} — {summary}"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("counts", "list", "index", "check"))
    parser.add_argument("--dir", default="docs/Testing/bugfunnel")
    parser.add_argument("--gap", choices=GAPS)
    parser.add_argument("--status", choices=STATUSES)
    parser.add_argument("--since")
    args = parser.parse_args()

    root = Path(args.dir)
    entries, problems = load(root / "entries")

    if args.command == "check":
        for problem in problems:
            print(problem)
        print(f"{len(entries)} entries, {len(problems)} problems")
        return 1 if problems else 0

    if problems:
        print(f"refusing to report over {len(problems)} invalid entries; "
              "run `bugfunnel.py check`", file=sys.stderr)
        return 1

    if args.command == "counts":
        for gap in GAPS:
            print(f"{gap}: {sum(1 for e in entries if e['gap'] == gap)}")
        print(f"TOTAL: {len(entries)}")
        for status in STATUSES:
            count = sum(1 for e in entries if e["status"] == status)
            if count:
                print(f"  {status}: {count}")
        return 0

    if args.command == "list":
        for entry in select(entries, args):
            print(one_line(entry))
        return 0

    lines = ["# Bug funnel index", "",
             "GENERATED by `scripts/bugfunnel.py index` — do not hand-edit.",
             "One escape per file under `entries/`; this is the scan sheet.", "",
             "| Gap | Total | Open |", "|---|---|---|"]
    for gap in GAPS:
        in_gap = [e for e in entries if e["gap"] == gap]
        open_count = sum(1 for e in in_gap if e["status"] in ("OPEN", "PARTIAL"))
        lines.append(f"| {gap} | {len(in_gap)} | {open_count} |")
    lines += ["", f"Total escapes: {len(entries)}", "", "## Entries (newest first)", ""]
    for entry in sorted(entries, key=lambda e: (str(e["date"]), e["id"]), reverse=True):
        lines.append(f"- {one_line(entry, limit=110)}")
    (root / "INDEX.md").write_text("\n".join(lines) + "\n")
    print(f"wrote {root / 'INDEX.md'} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
