#!/usr/bin/env python3
"""Generate docs/Architecture/CrateMap.md from archidoc IR snapshots.

The crate/frontend purposes are the `@c4` annotations in each crate's
`src/lib.rs` — that is the single source of truth. This script projects them
into a Markdown table; do not hand-edit the output. Regenerate with
`just arch-docs`.

Usage: gen-crate-map.py <crates.json> <frontends.json> <out.md>
"""
import json
import sys


def rows(ir_path, require_annotated):
    ir = json.load(open(ir_path))
    out = []
    for node in sorted(ir["root"].get("dirs", []), key=lambda n: n["name"]):
        desc = (node.get("description") or "").replace("\n", " ").strip()
        level = node.get("c4_level") or "—"
        if level == "unknown":
            level = "—"
        layer = node.get("layer") or "—"
        pattern = node.get("pattern") or "—"
        # Drop pure structural dirs archidoc found but that carry no annotation
        # (e.g. the Flutter FFI bridge, prototype frontends without a lib.rs).
        if require_annotated and level == "—" and not desc:
            continue
        out.append((node["name"], level, layer, pattern, desc))
    return out


def table(title, intro, data):
    lines = [f"## {title}", "", intro, "",
             "| Name | C4 | Layer | Pattern | Purpose |",
             "|------|----|-------|---------|---------|"]
    for name, level, layer, pattern, desc in data:
        purpose = desc or "_(undocumented — add a `//! @c4` block to its `src/lib.rs`)_"
        lines.append(f"| `{name}` | {level} | {layer} | {pattern} | {purpose} |")
    lines.append("")
    return "\n".join(lines)


def main():
    crates_json, frontends_json, out_md = sys.argv[1], sys.argv[2], sys.argv[3]
    header = (
        "<!-- GENERATED by `just arch-docs` from @c4 annotations in each crate's "
        "src/lib.rs. Do not edit by hand; edit the annotation and regenerate. -->\n\n"
        "# Crate & Frontend Map\n\n"
        "This inventory is compiled by [archidoc](https://github.com/GitSmart86/archidoc) "
        "from the `@c4` annotation at the top of each crate's `src/lib.rs`, and is "
        "checked against the committed baseline by `just arch-validate`.\n\n"
    )
    body = table(
        "Crates",
        "Library + binary crates under `crates/` (C4 components of the Holon system).",
        rows(crates_json, require_annotated=False),
    )
    body += "\n" + table(
        "Frontends",
        "Deployable apps under `frontends/` (C4 containers). Prototype/excluded "
        "frontends without an annotated `lib.rs` entry are omitted.",
        rows(frontends_json, require_annotated=True),
    )
    open(out_md, "w").write(header + body)
    print(f"wrote {out_md}")


if __name__ == "__main__":
    main()
