[package]
name = "holon-pbt-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "holon_pbt_core"
path = "src/lib.rs"

[dependencies]
proptest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
validated = "1.0"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
proptest-state-machine = { workspace = true }
