// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/ffi_bridge.dart';
import 'api/flutter_mutation_driver.dart';
import 'api/shared_pbt.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/holon_api.dart';
import 'third_party/holon_api/auth.dart';
import 'third_party/holon_api/block.dart';
import 'third_party/holon_api/document.dart';
import 'third_party/holon_api/entity.dart';
import 'third_party/holon_api/entity_uri.dart';
import 'third_party/holon_api/render_types.dart';
import 'third_party/holon_api/streaming.dart';
import 'third_party/holon_api/types.dart';
import 'third_party/holon_api/widget_spec.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcBoxPreconditionCheckerPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcFrontendSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ArcFnStringStringStringDartFnFuturePtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_EntityUriPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FfiWatchHandlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_FlutterMutationDriverPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SpanContextPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ArcBoxPreconditionChecker
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    dynamic raw,
  );

  @protected
  ArcFrontendSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    dynamic raw,
  );

  @protected
  ArcFnStringStringStringDartFnFuture
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    dynamic raw,
  );

  @protected
  EntityUri
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    dynamic raw,
  );

  @protected
  FfiWatchHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    dynamic raw,
  );

  @protected
  FlutterMutationDriver
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    dynamic raw,
  );

  @protected
  SpanContext
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    dynamic raw,
  );

  @protected
  EntityUri
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    dynamic raw,
  );

  @protected
  FfiWatchHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    dynamic raw,
  );

  @protected
  SpanContext
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    dynamic raw,
  );

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  FutureOr<void> Function(String, String, String)
  dco_decode_DartFn_Inputs_String_String_String_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  Map<String, RenderExpr> dco_decode_Map_String_render_expr_None(dynamic raw);

  @protected
  Map<String, Value> dco_decode_Map_String_value_None(dynamic raw);

  @protected
  ArcBoxPreconditionChecker
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    dynamic raw,
  );

  @protected
  ArcFrontendSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    dynamic raw,
  );

  @protected
  ArcFnStringStringStringDartFnFuture
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    dynamic raw,
  );

  @protected
  EntityUri
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    dynamic raw,
  );

  @protected
  FfiWatchHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    dynamic raw,
  );

  @protected
  FlutterMutationDriver
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    dynamic raw,
  );

  @protected
  SpanContext
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    dynamic raw,
  );

  @protected
  Set<String> dco_decode_Set_String_None(dynamic raw);

  @protected
  RustStreamSink<BatchMapChangeWithMetadata>
  dco_decode_StreamSink_batch_map_change_with_metadata_Sse(dynamic raw);

  @protected
  RustStreamSink<UiEvent> dco_decode_StreamSink_ui_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  HasSchema dco_decode_TraitDef_HasSchema(dynamic raw);

  @protected
  IntoEntity dco_decode_TraitDef_IntoEntity(dynamic raw);

  @protected
  ActionOperation dco_decode_action_operation(dynamic raw);

  @protected
  ActionSpec dco_decode_action_spec(dynamic raw);

  @protected
  Arg dco_decode_arg(dynamic raw);

  @protected
  BatchMapChange dco_decode_batch_map_change(dynamic raw);

  @protected
  BatchMapChangeWithMetadata dco_decode_batch_map_change_with_metadata(
    dynamic raw,
  );

  @protected
  BatchMetadata dco_decode_batch_metadata(dynamic raw);

  @protected
  BatchTraceContext dco_decode_batch_trace_context(dynamic raw);

  @protected
  BinaryOperator dco_decode_binary_operator(dynamic raw);

  @protected
  Block dco_decode_block(dynamic raw);

  @protected
  BlockContent dco_decode_block_content(dynamic raw);

  @protected
  BlockMetadata dco_decode_block_metadata(dynamic raw);

  @protected
  BlockResult dco_decode_block_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ArcBoxPreconditionChecker
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    dynamic raw,
  );

  @protected
  SpanContext
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    dynamic raw,
  );

  @protected
  BatchMapChangeWithMetadata
  dco_decode_box_autoadd_batch_map_change_with_metadata(dynamic raw);

  @protected
  BatchTraceContext dco_decode_box_autoadd_batch_trace_context(dynamic raw);

  @protected
  Block dco_decode_box_autoadd_block(dynamic raw);

  @protected
  BlockContent dco_decode_box_autoadd_block_content(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ChangeOrigin dco_decode_box_autoadd_change_origin(dynamic raw);

  @protected
  Document dco_decode_box_autoadd_document(dynamic raw);

  @protected
  EntityName dco_decode_box_autoadd_entity_name(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  FieldType dco_decode_box_autoadd_field_type(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  MapChangeSink dco_decode_box_autoadd_map_change_sink(dynamic raw);

  @protected
  QueryLanguage dco_decode_box_autoadd_query_language(dynamic raw);

  @protected
  (int, int) dco_decode_box_autoadd_record_u_32_u_32(dynamic raw);

  @protected
  RenderExpr dco_decode_box_autoadd_render_expr(dynamic raw);

  @protected
  RowProfile dco_decode_box_autoadd_row_profile(dynamic raw);

  @protected
  Schema dco_decode_box_autoadd_schema(dynamic raw);

  @protected
  SourceBlock dco_decode_box_autoadd_source_block(dynamic raw);

  @protected
  SourceLanguage dco_decode_box_autoadd_source_language(dynamic raw);

  @protected
  SyncTokenUpdate dco_decode_box_autoadd_sync_token_update(dynamic raw);

  @protected
  TaskState dco_decode_box_autoadd_task_state(dynamic raw);

  @protected
  TraceContext dco_decode_box_autoadd_trace_context(dynamic raw);

  @protected
  UiEventSink dco_decode_box_autoadd_ui_event_sink(dynamic raw);

  @protected
  UiInfo dco_decode_box_autoadd_ui_info(dynamic raw);

  @protected
  Value dco_decode_box_autoadd_value(dynamic raw);

  @protected
  WidgetSpec dco_decode_box_autoadd_widget_spec(dynamic raw);

  @protected
  RenderExpr dco_decode_box_render_expr(dynamic raw);

  @protected
  ChangeOrigin dco_decode_change_origin(dynamic raw);

  @protected
  ContentType dco_decode_content_type(dynamic raw);

  @protected
  Document dco_decode_document(dynamic raw);

  @protected
  DynamicEntity dco_decode_dynamic_entity(dynamic raw);

  @protected
  EntityFieldSchema dco_decode_entity_field_schema(dynamic raw);

  @protected
  EntityName dco_decode_entity_name(dynamic raw);

  @protected
  EntitySchema dco_decode_entity_schema(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FieldSchema dco_decode_field_schema(dynamic raw);

  @protected
  FieldType dco_decode_field_type(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  List<Map<String, Value>> dco_decode_list_Map_String_value_None(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActionSpec> dco_decode_list_action_spec(dynamic raw);

  @protected
  List<Arg> dco_decode_list_arg(dynamic raw);

  @protected
  List<EntityFieldSchema> dco_decode_list_entity_field_schema(dynamic raw);

  @protected
  List<FieldSchema> dco_decode_list_field_schema(dynamic raw);

  @protected
  List<List<Value>> dco_decode_list_list_value(dynamic raw);

  @protected
  List<MapChange> dco_decode_list_map_change(dynamic raw);

  @protected
  List<OperationDescriptor> dco_decode_list_operation_descriptor(dynamic raw);

  @protected
  List<OperationParam> dco_decode_list_operation_param(dynamic raw);

  @protected
  List<OperationWiring> dco_decode_list_operation_wiring(dynamic raw);

  @protected
  List<ParamMapping> dco_decode_list_param_mapping(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProviderAuthStatus> dco_decode_list_provider_auth_status(dynamic raw);

  @protected
  List<(String, RenderExpr)> dco_decode_list_record_string_render_expr(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(String, Value)> dco_decode_list_record_string_value(dynamic raw);

  @protected
  List<(String, Value, Value)> dco_decode_list_record_string_value_value(
    dynamic raw,
  );

  @protected
  List<RenderExpr> dco_decode_list_render_expr(dynamic raw);

  @protected
  List<ResolvedRow> dco_decode_list_resolved_row(dynamic raw);

  @protected
  List<Value> dco_decode_list_value(dynamic raw);

  @protected
  MapChange dco_decode_map_change(dynamic raw);

  @protected
  MapChangeSink dco_decode_map_change_sink(dynamic raw);

  @protected
  OperationDescriptor dco_decode_operation_descriptor(dynamic raw);

  @protected
  OperationParam dco_decode_operation_param(dynamic raw);

  @protected
  OperationWiring dco_decode_operation_wiring(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ArcBoxPreconditionChecker?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    dynamic raw,
  );

  @protected
  SpanContext?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    dynamic raw,
  );

  @protected
  BatchTraceContext? dco_decode_opt_box_autoadd_batch_trace_context(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  QueryLanguage? dco_decode_opt_box_autoadd_query_language(dynamic raw);

  @protected
  (int, int)? dco_decode_opt_box_autoadd_record_u_32_u_32(dynamic raw);

  @protected
  RowProfile? dco_decode_opt_box_autoadd_row_profile(dynamic raw);

  @protected
  SourceLanguage? dco_decode_opt_box_autoadd_source_language(dynamic raw);

  @protected
  SyncTokenUpdate? dco_decode_opt_box_autoadd_sync_token_update(dynamic raw);

  @protected
  TraceContext? dco_decode_opt_box_autoadd_trace_context(dynamic raw);

  @protected
  ParamMapping dco_decode_param_mapping(dynamic raw);

  @protected
  PreferencesRenderData dco_decode_preferences_render_data(dynamic raw);

  @protected
  Priority dco_decode_priority(dynamic raw);

  @protected
  ProviderAuthStatus dco_decode_provider_auth_status(dynamic raw);

  @protected
  QueryLanguage dco_decode_query_language(dynamic raw);

  @protected
  (String, RenderExpr) dco_decode_record_string_render_expr(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, Value) dco_decode_record_string_value(dynamic raw);

  @protected
  (String, Value, Value) dco_decode_record_string_value_value(dynamic raw);

  @protected
  (int, int) dco_decode_record_u_32_u_32(dynamic raw);

  @protected
  Region dco_decode_region(dynamic raw);

  @protected
  RenderExpr dco_decode_render_expr(dynamic raw);

  @protected
  ResolvedRow dco_decode_resolved_row(dynamic raw);

  @protected
  ResultOutput dco_decode_result_output(dynamic raw);

  @protected
  RowProfile dco_decode_row_profile(dynamic raw);

  @protected
  Schema dco_decode_schema(dynamic raw);

  @protected
  SourceBlock dco_decode_source_block(dynamic raw);

  @protected
  SourceLanguage dco_decode_source_language(dynamic raw);

  @protected
  StateCategory dco_decode_state_category(dynamic raw);

  @protected
  StreamPosition dco_decode_stream_position(dynamic raw);

  @protected
  SyncTokenUpdate dco_decode_sync_token_update(dynamic raw);

  @protected
  TaskState dco_decode_task_state(dynamic raw);

  @protected
  TraceContext dco_decode_trace_context(dynamic raw);

  @protected
  TypeHint dco_decode_type_hint(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  UiEvent dco_decode_ui_event(dynamic raw);

  @protected
  UiEventSink dco_decode_ui_event_sink(dynamic raw);

  @protected
  UiInfo dco_decode_ui_info(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Value dco_decode_value(dynamic raw);

  @protected
  WidgetSpec dco_decode_widget_spec(dynamic raw);

  @protected
  WidgetType dco_decode_widget_type(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ArcBoxPreconditionChecker
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    SseDeserializer deserializer,
  );

  @protected
  ArcFrontendSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    SseDeserializer deserializer,
  );

  @protected
  ArcFnStringStringStringDartFnFuture
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    SseDeserializer deserializer,
  );

  @protected
  EntityUri
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    SseDeserializer deserializer,
  );

  @protected
  FfiWatchHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterMutationDriver
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    SseDeserializer deserializer,
  );

  @protected
  SpanContext
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SseDeserializer deserializer,
  );

  @protected
  EntityUri
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    SseDeserializer deserializer,
  );

  @protected
  FfiWatchHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    SseDeserializer deserializer,
  );

  @protected
  SpanContext
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SseDeserializer deserializer,
  );

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, RenderExpr> sse_decode_Map_String_render_expr_None(
    SseDeserializer deserializer,
  );

  @protected
  Map<String, Value> sse_decode_Map_String_value_None(
    SseDeserializer deserializer,
  );

  @protected
  ArcBoxPreconditionChecker
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    SseDeserializer deserializer,
  );

  @protected
  ArcFrontendSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    SseDeserializer deserializer,
  );

  @protected
  ArcFnStringStringStringDartFnFuture
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    SseDeserializer deserializer,
  );

  @protected
  EntityUri
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    SseDeserializer deserializer,
  );

  @protected
  FfiWatchHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    SseDeserializer deserializer,
  );

  @protected
  FlutterMutationDriver
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    SseDeserializer deserializer,
  );

  @protected
  SpanContext
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SseDeserializer deserializer,
  );

  @protected
  Set<String> sse_decode_Set_String_None(SseDeserializer deserializer);

  @protected
  RustStreamSink<BatchMapChangeWithMetadata>
  sse_decode_StreamSink_batch_map_change_with_metadata_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<UiEvent> sse_decode_StreamSink_ui_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActionOperation sse_decode_action_operation(SseDeserializer deserializer);

  @protected
  ActionSpec sse_decode_action_spec(SseDeserializer deserializer);

  @protected
  Arg sse_decode_arg(SseDeserializer deserializer);

  @protected
  BatchMapChange sse_decode_batch_map_change(SseDeserializer deserializer);

  @protected
  BatchMapChangeWithMetadata sse_decode_batch_map_change_with_metadata(
    SseDeserializer deserializer,
  );

  @protected
  BatchMetadata sse_decode_batch_metadata(SseDeserializer deserializer);

  @protected
  BatchTraceContext sse_decode_batch_trace_context(
    SseDeserializer deserializer,
  );

  @protected
  BinaryOperator sse_decode_binary_operator(SseDeserializer deserializer);

  @protected
  Block sse_decode_block(SseDeserializer deserializer);

  @protected
  BlockContent sse_decode_block_content(SseDeserializer deserializer);

  @protected
  BlockMetadata sse_decode_block_metadata(SseDeserializer deserializer);

  @protected
  BlockResult sse_decode_block_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ArcBoxPreconditionChecker
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    SseDeserializer deserializer,
  );

  @protected
  SpanContext
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SseDeserializer deserializer,
  );

  @protected
  BatchMapChangeWithMetadata
  sse_decode_box_autoadd_batch_map_change_with_metadata(
    SseDeserializer deserializer,
  );

  @protected
  BatchTraceContext sse_decode_box_autoadd_batch_trace_context(
    SseDeserializer deserializer,
  );

  @protected
  Block sse_decode_box_autoadd_block(SseDeserializer deserializer);

  @protected
  BlockContent sse_decode_box_autoadd_block_content(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChangeOrigin sse_decode_box_autoadd_change_origin(
    SseDeserializer deserializer,
  );

  @protected
  Document sse_decode_box_autoadd_document(SseDeserializer deserializer);

  @protected
  EntityName sse_decode_box_autoadd_entity_name(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  FieldType sse_decode_box_autoadd_field_type(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MapChangeSink sse_decode_box_autoadd_map_change_sink(
    SseDeserializer deserializer,
  );

  @protected
  QueryLanguage sse_decode_box_autoadd_query_language(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_box_autoadd_record_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  RenderExpr sse_decode_box_autoadd_render_expr(SseDeserializer deserializer);

  @protected
  RowProfile sse_decode_box_autoadd_row_profile(SseDeserializer deserializer);

  @protected
  Schema sse_decode_box_autoadd_schema(SseDeserializer deserializer);

  @protected
  SourceBlock sse_decode_box_autoadd_source_block(SseDeserializer deserializer);

  @protected
  SourceLanguage sse_decode_box_autoadd_source_language(
    SseDeserializer deserializer,
  );

  @protected
  SyncTokenUpdate sse_decode_box_autoadd_sync_token_update(
    SseDeserializer deserializer,
  );

  @protected
  TaskState sse_decode_box_autoadd_task_state(SseDeserializer deserializer);

  @protected
  TraceContext sse_decode_box_autoadd_trace_context(
    SseDeserializer deserializer,
  );

  @protected
  UiEventSink sse_decode_box_autoadd_ui_event_sink(
    SseDeserializer deserializer,
  );

  @protected
  UiInfo sse_decode_box_autoadd_ui_info(SseDeserializer deserializer);

  @protected
  Value sse_decode_box_autoadd_value(SseDeserializer deserializer);

  @protected
  WidgetSpec sse_decode_box_autoadd_widget_spec(SseDeserializer deserializer);

  @protected
  RenderExpr sse_decode_box_render_expr(SseDeserializer deserializer);

  @protected
  ChangeOrigin sse_decode_change_origin(SseDeserializer deserializer);

  @protected
  ContentType sse_decode_content_type(SseDeserializer deserializer);

  @protected
  Document sse_decode_document(SseDeserializer deserializer);

  @protected
  DynamicEntity sse_decode_dynamic_entity(SseDeserializer deserializer);

  @protected
  EntityFieldSchema sse_decode_entity_field_schema(
    SseDeserializer deserializer,
  );

  @protected
  EntityName sse_decode_entity_name(SseDeserializer deserializer);

  @protected
  EntitySchema sse_decode_entity_schema(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FieldSchema sse_decode_field_schema(SseDeserializer deserializer);

  @protected
  FieldType sse_decode_field_type(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  List<Map<String, Value>> sse_decode_list_Map_String_value_None(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActionSpec> sse_decode_list_action_spec(SseDeserializer deserializer);

  @protected
  List<Arg> sse_decode_list_arg(SseDeserializer deserializer);

  @protected
  List<EntityFieldSchema> sse_decode_list_entity_field_schema(
    SseDeserializer deserializer,
  );

  @protected
  List<FieldSchema> sse_decode_list_field_schema(SseDeserializer deserializer);

  @protected
  List<List<Value>> sse_decode_list_list_value(SseDeserializer deserializer);

  @protected
  List<MapChange> sse_decode_list_map_change(SseDeserializer deserializer);

  @protected
  List<OperationDescriptor> sse_decode_list_operation_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<OperationParam> sse_decode_list_operation_param(
    SseDeserializer deserializer,
  );

  @protected
  List<OperationWiring> sse_decode_list_operation_wiring(
    SseDeserializer deserializer,
  );

  @protected
  List<ParamMapping> sse_decode_list_param_mapping(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProviderAuthStatus> sse_decode_list_provider_auth_status(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, RenderExpr)> sse_decode_list_record_string_render_expr(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Value)> sse_decode_list_record_string_value(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, Value, Value)> sse_decode_list_record_string_value_value(
    SseDeserializer deserializer,
  );

  @protected
  List<RenderExpr> sse_decode_list_render_expr(SseDeserializer deserializer);

  @protected
  List<ResolvedRow> sse_decode_list_resolved_row(SseDeserializer deserializer);

  @protected
  List<Value> sse_decode_list_value(SseDeserializer deserializer);

  @protected
  MapChange sse_decode_map_change(SseDeserializer deserializer);

  @protected
  MapChangeSink sse_decode_map_change_sink(SseDeserializer deserializer);

  @protected
  OperationDescriptor sse_decode_operation_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  OperationParam sse_decode_operation_param(SseDeserializer deserializer);

  @protected
  OperationWiring sse_decode_operation_wiring(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ArcBoxPreconditionChecker?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    SseDeserializer deserializer,
  );

  @protected
  SpanContext?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SseDeserializer deserializer,
  );

  @protected
  BatchTraceContext? sse_decode_opt_box_autoadd_batch_trace_context(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  QueryLanguage? sse_decode_opt_box_autoadd_query_language(
    SseDeserializer deserializer,
  );

  @protected
  (int, int)? sse_decode_opt_box_autoadd_record_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  RowProfile? sse_decode_opt_box_autoadd_row_profile(
    SseDeserializer deserializer,
  );

  @protected
  SourceLanguage? sse_decode_opt_box_autoadd_source_language(
    SseDeserializer deserializer,
  );

  @protected
  SyncTokenUpdate? sse_decode_opt_box_autoadd_sync_token_update(
    SseDeserializer deserializer,
  );

  @protected
  TraceContext? sse_decode_opt_box_autoadd_trace_context(
    SseDeserializer deserializer,
  );

  @protected
  ParamMapping sse_decode_param_mapping(SseDeserializer deserializer);

  @protected
  PreferencesRenderData sse_decode_preferences_render_data(
    SseDeserializer deserializer,
  );

  @protected
  Priority sse_decode_priority(SseDeserializer deserializer);

  @protected
  ProviderAuthStatus sse_decode_provider_auth_status(
    SseDeserializer deserializer,
  );

  @protected
  QueryLanguage sse_decode_query_language(SseDeserializer deserializer);

  @protected
  (String, RenderExpr) sse_decode_record_string_render_expr(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, Value) sse_decode_record_string_value(SseDeserializer deserializer);

  @protected
  (String, Value, Value) sse_decode_record_string_value_value(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_record_u_32_u_32(SseDeserializer deserializer);

  @protected
  Region sse_decode_region(SseDeserializer deserializer);

  @protected
  RenderExpr sse_decode_render_expr(SseDeserializer deserializer);

  @protected
  ResolvedRow sse_decode_resolved_row(SseDeserializer deserializer);

  @protected
  ResultOutput sse_decode_result_output(SseDeserializer deserializer);

  @protected
  RowProfile sse_decode_row_profile(SseDeserializer deserializer);

  @protected
  Schema sse_decode_schema(SseDeserializer deserializer);

  @protected
  SourceBlock sse_decode_source_block(SseDeserializer deserializer);

  @protected
  SourceLanguage sse_decode_source_language(SseDeserializer deserializer);

  @protected
  StateCategory sse_decode_state_category(SseDeserializer deserializer);

  @protected
  StreamPosition sse_decode_stream_position(SseDeserializer deserializer);

  @protected
  SyncTokenUpdate sse_decode_sync_token_update(SseDeserializer deserializer);

  @protected
  TaskState sse_decode_task_state(SseDeserializer deserializer);

  @protected
  TraceContext sse_decode_trace_context(SseDeserializer deserializer);

  @protected
  TypeHint sse_decode_type_hint(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  UiEvent sse_decode_ui_event(SseDeserializer deserializer);

  @protected
  UiEventSink sse_decode_ui_event_sink(SseDeserializer deserializer);

  @protected
  UiInfo sse_decode_ui_info(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Value sse_decode_value(SseDeserializer deserializer);

  @protected
  WidgetSpec sse_decode_widget_spec(SseDeserializer deserializer);

  @protected
  WidgetType sse_decode_widget_type(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    ArcBoxPreconditionChecker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    ArcFrontendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    ArcFnStringStringStringDartFnFuture self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    EntityUri self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    FfiWatchHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    FlutterMutationDriver self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SpanContext self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    EntityUri self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    FfiWatchHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SpanContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void
  sse_encode_DartFn_Inputs_String_String_String_Output_unit_AnyhowException(
    FutureOr<void> Function(String, String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_render_expr_None(
    Map<String, RenderExpr> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_value_None(
    Map<String, Value> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    ArcBoxPreconditionChecker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    ArcFrontendSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    ArcFnStringStringStringDartFnFuture self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    EntityUri self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    FfiWatchHandle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    FlutterMutationDriver self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SpanContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Set_String_None(Set<String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_batch_map_change_with_metadata_Sse(
    RustStreamSink<BatchMapChangeWithMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ui_event_Sse(
    RustStreamSink<UiEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_action_operation(
    ActionOperation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_action_spec(ActionSpec self, SseSerializer serializer);

  @protected
  void sse_encode_arg(Arg self, SseSerializer serializer);

  @protected
  void sse_encode_batch_map_change(
    BatchMapChange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_map_change_with_metadata(
    BatchMapChangeWithMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_metadata(BatchMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_batch_trace_context(
    BatchTraceContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binary_operator(
    BinaryOperator self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_block(Block self, SseSerializer serializer);

  @protected
  void sse_encode_block_content(BlockContent self, SseSerializer serializer);

  @protected
  void sse_encode_block_metadata(BlockMetadata self, SseSerializer serializer);

  @protected
  void sse_encode_block_result(BlockResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    ArcBoxPreconditionChecker self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SpanContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_batch_map_change_with_metadata(
    BatchMapChangeWithMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_batch_trace_context(
    BatchTraceContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_block(Block self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_block_content(
    BlockContent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_change_origin(
    ChangeOrigin self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_document(Document self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_entity_name(
    EntityName self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_field_type(
    FieldType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_map_change_sink(
    MapChangeSink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_query_language(
    QueryLanguage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_32_u_32(
    (int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_render_expr(
    RenderExpr self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_row_profile(
    RowProfile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_schema(Schema self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_source_block(
    SourceBlock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_source_language(
    SourceLanguage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_token_update(
    SyncTokenUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_state(
    TaskState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_trace_context(
    TraceContext self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_event_sink(
    UiEventSink self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ui_info(UiInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_value(Value self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_widget_spec(
    WidgetSpec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_render_expr(RenderExpr self, SseSerializer serializer);

  @protected
  void sse_encode_change_origin(ChangeOrigin self, SseSerializer serializer);

  @protected
  void sse_encode_content_type(ContentType self, SseSerializer serializer);

  @protected
  void sse_encode_document(Document self, SseSerializer serializer);

  @protected
  void sse_encode_dynamic_entity(DynamicEntity self, SseSerializer serializer);

  @protected
  void sse_encode_entity_field_schema(
    EntityFieldSchema self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entity_name(EntityName self, SseSerializer serializer);

  @protected
  void sse_encode_entity_schema(EntitySchema self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_field_schema(FieldSchema self, SseSerializer serializer);

  @protected
  void sse_encode_field_type(FieldType self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_Map_String_value_None(
    List<Map<String, Value>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_action_spec(
    List<ActionSpec> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_arg(List<Arg> self, SseSerializer serializer);

  @protected
  void sse_encode_list_entity_field_schema(
    List<EntityFieldSchema> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_field_schema(
    List<FieldSchema> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_value(
    List<List<Value>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_map_change(
    List<MapChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_operation_descriptor(
    List<OperationDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_operation_param(
    List<OperationParam> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_operation_wiring(
    List<OperationWiring> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_param_mapping(
    List<ParamMapping> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_provider_auth_status(
    List<ProviderAuthStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_render_expr(
    List<(String, RenderExpr)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_value(
    List<(String, Value)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_value_value(
    List<(String, Value, Value)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_render_expr(
    List<RenderExpr> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resolved_row(
    List<ResolvedRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_value(List<Value> self, SseSerializer serializer);

  @protected
  void sse_encode_map_change(MapChange self, SseSerializer serializer);

  @protected
  void sse_encode_map_change_sink(MapChangeSink self, SseSerializer serializer);

  @protected
  void sse_encode_operation_descriptor(
    OperationDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_operation_param(
    OperationParam self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_operation_wiring(
    OperationWiring self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    ArcBoxPreconditionChecker? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    SpanContext? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_batch_trace_context(
    BatchTraceContext? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_query_language(
    QueryLanguage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_u_32_u_32(
    (int, int)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_row_profile(
    RowProfile? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_source_language(
    SourceLanguage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_sync_token_update(
    SyncTokenUpdate? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_trace_context(
    TraceContext? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_param_mapping(ParamMapping self, SseSerializer serializer);

  @protected
  void sse_encode_preferences_render_data(
    PreferencesRenderData self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_priority(Priority self, SseSerializer serializer);

  @protected
  void sse_encode_provider_auth_status(
    ProviderAuthStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_query_language(QueryLanguage self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_render_expr(
    (String, RenderExpr) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_value(
    (String, Value) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_value_value(
    (String, Value, Value) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_32_u_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_region(Region self, SseSerializer serializer);

  @protected
  void sse_encode_render_expr(RenderExpr self, SseSerializer serializer);

  @protected
  void sse_encode_resolved_row(ResolvedRow self, SseSerializer serializer);

  @protected
  void sse_encode_result_output(ResultOutput self, SseSerializer serializer);

  @protected
  void sse_encode_row_profile(RowProfile self, SseSerializer serializer);

  @protected
  void sse_encode_schema(Schema self, SseSerializer serializer);

  @protected
  void sse_encode_source_block(SourceBlock self, SseSerializer serializer);

  @protected
  void sse_encode_source_language(
    SourceLanguage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_state_category(StateCategory self, SseSerializer serializer);

  @protected
  void sse_encode_stream_position(
    StreamPosition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_token_update(
    SyncTokenUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_task_state(TaskState self, SseSerializer serializer);

  @protected
  void sse_encode_trace_context(TraceContext self, SseSerializer serializer);

  @protected
  void sse_encode_type_hint(TypeHint self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_ui_event(UiEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ui_event_sink(UiEventSink self, SseSerializer serializer);

  @protected
  void sse_encode_ui_info(UiInfo self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_value(Value self, SseSerializer serializer);

  @protected
  void sse_encode_widget_spec(WidgetSpec self, SseSerializer serializer);

  @protected
  void sse_encode_widget_type(WidgetType self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcBoxPreconditionChecker(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcFrontendSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerArcdynFnStringStringStringDartFnFutureSendSync(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerEntityUri(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFfiWatchHandle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerFlutterMutationDriver(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSpanContext(
    int ptr,
  );
}
