//! Render DSL: Rhai-based language for defining render expressions.
//!
//! Render source blocks contain Rhai expressions that produce a render tree.
//! Each widget function (columns, list, tree, text, icon, etc.) is registered
//! as a Rhai function that returns a Dynamic map describing a RenderExpr node.
//!
//! ## Widget registry seam
//!
//! Adding a new widget like `kanban`, `calendar`, or a parametric-style
//! function does **not** require touching the `RenderExpr` enum or this parser.
//! The seam:
//!
//! 1. Parse-time: every identifier-followed-by-`(` in the source is treated as
//!    a widget call. The parser scans the source for such names and registers
//!    them with Rhai automatically. New names need no explicit registration.
//! 2. Interpret-time: the frontend's shadow builder registry (auto-generated by
//!    `holon_macros::builder_registry!`) resolves the widget name to a builder.
//!    A new widget appears by adding a builder file under
//!    `crates/holon-frontend/src/shadow_builders/`.
//!
//! `register_widget_names` is an *optional* hint used by the frontend to seed
//! the engine with the canonical set up-front. The parser falls back to
//! source-driven discovery when names aren't pre-registered (tests, headless
//! backend code).
//!
//! ## Syntax examples
//!
//! ```rhai
//! columns(#{gap: 4, item_template: live_block()})
//!
//! list(#{sortkey: "name", item_template: render_entity()})
//!
//! tree(#{parent_id: col("parent_id"), sortkey: col("id"), item_template: render_entity()})
//!
//! list(#{item_template: selectable(
//!     row(icon("folder"), spacer(6), text(col("name"))),
//!     #{action: navigation_focus(#{region: "main", block_id: col("doc_uri")})}
//! )})
//! ```
//!
//! ## Special functions
//!
//! - `col("name")` — column reference (resolved per-row at render time)
//! - All other functions map to RenderExpr::FunctionCall nodes

use std::collections::HashMap;
use std::sync::OnceLock;

use anyhow::Context;
use anyhow::Result;
use rhai::Dynamic;
use rhai::Engine as RhaiEngine;
use rhai::Map as RhaiMap;

use crate::Value;
use crate::render_types::Arg;
use crate::render_types::RenderExpr;

/// Global widget name registry. **Optional hint** populated by the frontend at
/// startup via `register_widget_names()`. Callers that don't reach the
/// frontend (backend tests, headless engines, action_watcher) get the same
/// behavior because `parse_render_dsl()` also scans the source for any
/// identifier-in-call-position and registers it ad hoc.
static WIDGET_NAMES: OnceLock<Vec<String>> = OnceLock::new();

/// Pre-register the canonical widget name list with the parser (optional hint).
///
/// Called at startup by the frontend, passing the auto-generated
/// `builder_names()` from the shadow builder registry. Subsequent calls are
/// ignored (OnceLock semantics). When this isn't called (tests, backend-only
/// code), `parse_render_dsl()` discovers names from the source itself.
pub fn register_widget_names(names: &[&str]) {
    let _ = WIDGET_NAMES.set(names.iter().map(|s| s.to_string()).collect());
}

/// Get the pre-registered widget names. Returns `&[]` if
/// `register_widget_names` was never called — callers must combine with
/// `extract_function_names(source)` before parsing, which `parse_render_dsl()`
/// does automatically.
pub fn registered_widget_names() -> &'static [String] {
    static EMPTY: Vec<String> = Vec::new();
    WIDGET_NAMES.get().unwrap_or(&EMPTY)
}

/// Parse a render DSL string into a RenderExpr.
///
/// Discovers widget names by union of:
/// (a) names pre-registered via `register_widget_names()` (frontend startup),
/// and (b) identifier-in-call-position tokens scanned from `source` itself.
///
/// The second source means new widgets like `kanban(#{...})` parse without any
/// registration — the frontend needs to add the builder, but the parser is
/// extension-free.
pub fn parse_render_dsl(source: &str) -> Result<RenderExpr> {
    let mut names: Vec<String> = registered_widget_names().to_vec();
    for name in extract_function_names(source) {
        if !names.iter().any(|n| n == &name) {
            names.push(name);
        }
    }
    let name_refs: Vec<&str> = names.iter().map(String::as_str).collect();
    parse_render_dsl_with_engine(source, &create_render_engine_with_names(&name_refs))
}

/// Parse a render DSL string using an explicit set of widget names.
///
/// Used by the frontend's `RenderInterpreter::parse_dsl` which already has the
/// builder registry on hand. Source-extracted names are still unioned in so
/// new widgets in the source parse without an explicit registry update.
pub fn parse_render_dsl_with_names(source: &str, names: &[&str]) -> Result<RenderExpr> {
    let mut all: Vec<String> = names.iter().map(|s| (*s).to_string()).collect();
    for name in extract_function_names(source) {
        if !all.iter().any(|n| n == &name) {
            all.push(name);
        }
    }
    let name_refs: Vec<&str> = all.iter().map(String::as_str).collect();
    parse_render_dsl_with_engine(source, &create_render_engine_with_names(&name_refs))
}

/// Rhai keywords / built-ins that must NOT be registered as widget functions.
/// Registering these would either fail or shadow language constructs.
const RHAI_RESERVED: &[&str] = &[
    "if", "else", "for", "in", "while", "do", "loop", "until", "break", "continue", "return", "fn",
    "let", "const", "private", "true", "false", "null", "switch", "try", "catch", "throw",
    "import", "export", "as", "is", "this",
];

/// Scan a Rhai source for identifiers in function-call position (`name(`).
///
/// Skips string literals (single/double quoted) and `//` line comments so
/// occurrences inside `text("foo(bar)")` don't false-positive. Filters out
/// Rhai reserved words. Used by `parse_render_dsl` to bootstrap the engine
/// with widget functions for any name the source mentions, eliminating the
/// need to update a global registry when adding a new widget.
fn extract_function_names(source: &str) -> Vec<String> {
    let bytes = source.as_bytes();
    let mut names: Vec<String> = Vec::new();
    let mut i = 0;
    while i < bytes.len() {
        let c = bytes[i];
        // Skip string literals
        if c == b'"' || c == b'\'' {
            let quote = c;
            i += 1;
            while i < bytes.len() && bytes[i] != quote {
                if bytes[i] == b'\\' && i + 1 < bytes.len() {
                    i += 2;
                } else {
                    i += 1;
                }
            }
            if i < bytes.len() {
                i += 1;
            }
            continue;
        }
        // Skip `//` line comments
        if c == b'/' && i + 1 < bytes.len() && bytes[i + 1] == b'/' {
            while i < bytes.len() && bytes[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        // Identifier start: letter or underscore
        if c == b'_' || c.is_ascii_alphabetic() {
            let start = i;
            while i < bytes.len() && (bytes[i] == b'_' || bytes[i].is_ascii_alphanumeric()) {
                i += 1;
            }
            let id_end = i;
            // Skip whitespace between identifier and `(`
            while i < bytes.len() && bytes[i].is_ascii_whitespace() {
                i += 1;
            }
            if i < bytes.len() && bytes[i] == b'(' {
                let name = &source[start..id_end];
                if !RHAI_RESERVED.contains(&name) && !names.iter().any(|n| n == name) {
                    names.push(name.to_string());
                }
            }
            continue;
        }
        i += 1;
    }
    names
}

fn parse_render_dsl_with_engine(source: &str, engine: &RhaiEngine) -> Result<RenderExpr> {
    let trimmed = source.trim();
    if trimmed.is_empty() {
        return Ok(default_table());
    }

    // Try JSON first (backwards compat)
    if let Ok(expr) = serde_json::from_str::<RenderExpr>(trimmed) {
        return Ok(expr);
    }

    let result = engine
        .eval_expression::<Dynamic>(trimmed)
        .map_err(|e| anyhow::anyhow!("Failed to parse render DSL '{}': {e}", trimmed))?;

    dynamic_to_render_expr(&result)
        .with_context(|| format!("Failed to convert Rhai result to RenderExpr: {:?}", result))
}

fn default_table() -> RenderExpr {
    RenderExpr::FunctionCall {
        name: "table".to_string(),
        args: Vec::new(),
    }
}

/// Create a Rhai engine with all render functions registered.
///
/// Widget names come from `registered_widget_names()` (the optional frontend
/// hint set via `register_widget_names()`). When no names are pre-registered
/// the engine carries only `col(...)`; callers that need to evaluate widget
/// calls should prefer `parse_render_dsl()` (which adds source-extracted
/// names) or `create_render_engine_with_names()` with an explicit list.
pub fn create_render_engine() -> RhaiEngine {
    create_render_engine_with_names(registered_widget_names())
}

/// Create a Rhai engine with an explicit set of widget names.
pub fn create_render_engine_with_names(widget_names: &[impl AsRef<str>]) -> RhaiEngine {
    let mut engine = RhaiEngine::new();

    // col("name") → ColumnRef marker
    engine.register_fn("col", |name: &str| -> Dynamic {
        let mut map = RhaiMap::new();
        map.insert("_type".into(), "col".into());
        map.insert("name".into(), Dynamic::from(name.to_string()));
        Dynamic::from(map)
    });

    for name in widget_names {
        register_widget_fn(&mut engine, name.as_ref());
    }

    // Predicate constructors. Each produces a Rhai map matching the
    // `Predicate` enum's serde external-tagged shape (`#[serde(rename_all =
    // "snake_case")]`), so the rule evaluator's `parse_rules_arg` round-trip
    // (see `render_interpreter.rs::parse_rules_arg`) deserializes cleanly.
    //
    // Used inside `tree(rules: [#{when: eq("level", 0), override: ...}])`
    // and similar predicate-driven constructs.
    //
    // Registered AFTER the widget loop on purpose: source-driven
    // discovery in `parse_render_dsl_with_names` may have added these
    // names to `widget_names` (any identifier-followed-by-`(` is treated
    // as a widget call). Registering predicates last makes the
    // predicate-shaped output win for matching signatures.
    //
    // `Predicate::Var` is intentionally not registered — `var` is a Rhai
    // reserved keyword and the tokenizer rejects it before dispatch.
    // Users who need `Predicate::Var` write the verbose form
    // `#{var: "field_name"}` directly.
    register_binary_predicate(&mut engine, "eq");
    register_binary_predicate(&mut engine, "ne");
    register_binary_predicate(&mut engine, "gt");
    register_binary_predicate(&mut engine, "lt");
    register_binary_predicate(&mut engine, "gte");
    register_binary_predicate(&mut engine, "lte");
    register_string_predicate(&mut engine, "is_not_null");
    register_n_ary_predicate(&mut engine, "and");
    register_n_ary_predicate(&mut engine, "or");
    engine.register_fn("not", |pred: Dynamic| -> Dynamic {
        let mut outer = RhaiMap::new();
        outer.insert("not".into(), pred);
        Dynamic::from(outer)
    });
    // Unit variant — Predicate::Always serializes as the bare string
    // `"always"` under default external tagging.
    engine.register_fn("always", || -> Dynamic {
        Dynamic::from("always".to_string())
    });

    // Dotted names: Rhai doesn't allow dots in function names,
    // so users write underscores and we map to the dotted name.
    register_widget_fn_aliased(&mut engine, "navigation_focus", "navigation.focus");
    register_widget_fn_aliased(&mut engine, "focus_pin", "navigation.focus_pin");
    register_widget_fn_aliased(&mut engine, "navigation_close", "navigation.close");
    register_widget_fn_aliased(&mut engine, "navigation_activate", "navigation.activate");
    register_widget_fn_aliased(&mut engine, "navigation_open_tab", "navigation.open_tab");
    register_widget_fn_aliased(
        &mut engine,
        "answer_question",
        "pending_question.answer_question",
    );
    register_widget_fn_aliased(&mut engine, "send_message", "session.send_message");

    engine
}

/// Register a binary predicate (`eq`/`ne`/`gt`/`lt`/`gte`/`lte`).
///
/// All share the `{<key>: {field: <name>, value: <v>}}` serde shape, matching
/// `Predicate::Eq { field, value }` and friends.
fn register_binary_predicate(engine: &mut RhaiEngine, name: &'static str) {
    engine.register_fn(name, move |field: &str, value: Dynamic| -> Dynamic {
        let mut inner = RhaiMap::new();
        inner.insert("field".into(), Dynamic::from(field.to_string()));
        inner.insert("value".into(), value);
        let mut outer = RhaiMap::new();
        outer.insert(name.into(), Dynamic::from(inner));
        Dynamic::from(outer)
    });
}

/// Register a single-string-payload predicate (`var`/`is_not_null`).
///
/// Both share the `{<key>: <field>}` serde shape, matching
/// `Predicate::Var(String)` / `Predicate::IsNotNull(String)`.
fn register_string_predicate(engine: &mut RhaiEngine, name: &'static str) {
    engine.register_fn(name, move |field: &str| -> Dynamic {
        let mut outer = RhaiMap::new();
        outer.insert(name.into(), Dynamic::from(field.to_string()));
        Dynamic::from(outer)
    });
}

/// Register an n-ary predicate (`and`/`or`) for arities 1..=6.
///
/// Rhai has no variadic syntax; we register one overload per arity to cover
/// realistic predicate stacks. Beyond 6 children, users can nest
/// (`and(and(p1, p2, p3), p4)`).
///
/// Output shape `{<key>: [<preds>]}` matches `Predicate::And(Vec<Predicate>)`
/// / `Predicate::Or(Vec<Predicate>)`.
fn register_n_ary_predicate(engine: &mut RhaiEngine, name: &'static str) {
    fn pack(name: &str, preds: Vec<Dynamic>) -> Dynamic {
        let arr: rhai::Array = preds;
        let mut outer = RhaiMap::new();
        outer.insert(name.into(), Dynamic::from(arr));
        Dynamic::from(outer)
    }
    engine.register_fn(name, move |a: Dynamic| -> Dynamic { pack(name, vec![a]) });
    engine.register_fn(name, move |a: Dynamic, b: Dynamic| -> Dynamic {
        pack(name, vec![a, b])
    });
    engine.register_fn(name, move |a: Dynamic, b: Dynamic, c: Dynamic| -> Dynamic {
        pack(name, vec![a, b, c])
    });
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic| -> Dynamic {
            pack(name, vec![a, b, c, d])
        },
    );
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic, e: Dynamic| -> Dynamic {
            pack(name, vec![a, b, c, d, e])
        },
    );
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic, e: Dynamic, f: Dynamic| -> Dynamic {
            pack(name, vec![a, b, c, d, e, f])
        },
    );
}

/// Register a widget function where the Rhai name differs from the output name.
/// E.g., `navigation_focus` in Rhai → `navigation.focus` in RenderExpr.
fn register_widget_fn_aliased(engine: &mut RhaiEngine, rhai_name: &str, output_name: &str) {
    let n = output_name.to_string();

    let n0 = n.clone();
    engine.register_fn(rhai_name, move || -> Dynamic { make_fn_node(&n0, vec![]) });
    let n1 = n.clone();
    engine.register_fn(rhai_name, move |a: Dynamic| -> Dynamic {
        make_fn_node(&n1, vec![a])
    });
    let n2 = n.clone();
    engine.register_fn(rhai_name, move |a: Dynamic, b: Dynamic| -> Dynamic {
        make_fn_node(&n2, vec![a, b])
    });
    let n3 = n.clone();
    engine.register_fn(
        rhai_name,
        move |a: Dynamic, b: Dynamic, c: Dynamic| -> Dynamic { make_fn_node(&n3, vec![a, b, c]) },
    );
}

fn register_widget_fn(engine: &mut RhaiEngine, name: &str) {
    let n = name.to_string();

    // 0-arg: live_block()
    let n0 = n.clone();
    engine.register_fn(name, move || -> Dynamic { make_fn_node(&n0, vec![]) });

    // 1-arg: columns(#{gap: 4}) or text("hello") or text(col("name"))
    let n1 = n.clone();
    engine.register_fn(name, move |arg: Dynamic| -> Dynamic {
        make_fn_node(&n1, vec![arg])
    });

    // 2-arg: selectable(child, #{action: ...})
    let n2 = n.clone();
    engine.register_fn(name, move |a: Dynamic, b: Dynamic| -> Dynamic {
        make_fn_node(&n2, vec![a, b])
    });

    // 3-arg: row(a, b, c)
    let n3 = n.clone();
    engine.register_fn(name, move |a: Dynamic, b: Dynamic, c: Dynamic| -> Dynamic {
        make_fn_node(&n3, vec![a, b, c])
    });

    // 4-arg
    let n4 = n.clone();
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic| -> Dynamic {
            make_fn_node(&n4, vec![a, b, c, d])
        },
    );

    // 5-arg
    let n5 = n.clone();
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic, e: Dynamic| -> Dynamic {
            make_fn_node(&n5, vec![a, b, c, d, e])
        },
    );

    // 6-arg
    let n6 = n.clone();
    engine.register_fn(
        name,
        move |a: Dynamic, b: Dynamic, c: Dynamic, d: Dynamic, e: Dynamic, f: Dynamic| -> Dynamic {
            make_fn_node(&n6, vec![a, b, c, d, e, f])
        },
    );
}

/// Build a function node Dynamic.
///
/// Convention: the LAST Map argument is treated as named args.
/// All other arguments are positional.
fn make_fn_node(name: &str, args: Vec<Dynamic>) -> Dynamic {
    let mut map = RhaiMap::new();
    map.insert("_type".into(), "fn".into());
    map.insert("_name".into(), Dynamic::from(name.to_string()));

    let mut positional = Vec::new();
    let mut named = RhaiMap::new();

    for arg in args.into_iter() {
        if arg.is_map() {
            // Check if it's a col() marker or a fn node — those are positional
            let m = arg.clone().cast::<RhaiMap>();
            if m.contains_key("_type") {
                positional.push(arg);
            } else {
                // Plain map = named args (merge into named)
                for (k, v) in m {
                    named.insert(k, v);
                }
            }
        } else {
            positional.push(arg);
        }
    }

    map.insert("_positional".into(), Dynamic::from(positional));
    map.insert("_named".into(), Dynamic::from(named));
    Dynamic::from(map)
}

// ---------------------------------------------------------------------------
// Dynamic → RenderExpr conversion
// ---------------------------------------------------------------------------

pub fn dynamic_to_render_expr(d: &Dynamic) -> Result<RenderExpr> {
    if d.is_map() {
        let map = d.clone().cast::<RhaiMap>();

        let typ = map
            .get("_type")
            .and_then(|v| v.clone().into_string().ok()) // ALLOW(ok): non-string → None
            .unwrap_or_default();

        match typ.as_str() {
            "fn" => map_to_function_call(&map),
            "col" => {
                let name = map
                    .get("name")
                    .and_then(|v| v.clone().into_string().ok()) // ALLOW(ok): non-string → None
                    .unwrap_or_default();
                Ok(RenderExpr::ColumnRef { name })
            }
            _ => {
                // Plain map without _type — treat as Object
                let mut fields = HashMap::new();
                for (k, v) in &map {
                    fields.insert(k.to_string(), dynamic_to_render_expr(v)?);
                }
                Ok(RenderExpr::Object { fields })
            }
        }
    } else if d.is_array() {
        let arr = d.clone().cast::<Vec<Dynamic>>();
        let items: Result<Vec<_>> = arr.iter().map(dynamic_to_render_expr).collect();
        Ok(RenderExpr::Array { items: items? })
    } else {
        // Primitive → Literal
        Ok(RenderExpr::Literal {
            value: dynamic_to_value(d),
        })
    }
}

fn map_to_function_call(map: &RhaiMap) -> Result<RenderExpr> {
    let name = map
        .get("_name")
        .ok_or_else(|| anyhow::anyhow!("render function map missing `_name` field"))?
        .clone()
        .into_string()
        .map_err(|_| anyhow::anyhow!("render function `_name` must be a string"))?;

    let mut args = Vec::new();

    // Named args
    if let Some(named_dyn) = map.get("_named").filter(|d| d.is_map()) {
        let named = named_dyn.clone().cast::<RhaiMap>();
        for (k, v) in &named {
            args.push(Arg {
                name: Some(k.to_string()),
                value: dynamic_to_render_expr(v)?,
            });
        }
    }

    // Positional args
    if let Some(pos_dyn) = map.get("_positional").filter(|d| d.is_array()) {
        let positional = pos_dyn.clone().cast::<Vec<Dynamic>>();
        for v in &positional {
            args.push(Arg {
                name: None,
                value: dynamic_to_render_expr(v)?,
            });
        }
    }

    Ok(RenderExpr::FunctionCall { name, args })
}

fn dynamic_to_value(d: &Dynamic) -> Value {
    if d.is_int() {
        Value::Integer(d.as_int().unwrap())
    } else if d.is_float() {
        Value::Float(d.as_float().unwrap())
    } else if d.is_bool() {
        Value::Boolean(d.as_bool().unwrap())
    } else if d.is_string() {
        Value::String(d.clone().into_string().unwrap())
    } else if d.is_unit() {
        Value::Null
    } else {
        Value::String(format!("{d:?}"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(source: &str) -> Result<RenderExpr> {
        register_widget_names(&[
            "table",
            "live_block",
            "columns",
            "text",
            "row",
            "icon",
            "spacer",
            "tree",
            "render_entity",
            "list",
            "selectable",
            "chain_ops",
        ]);
        parse_render_dsl(source)
    }

    #[test]
    fn test_simple_function() {
        let expr = parse("table()").unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));
    }

    #[test]
    fn test_live_block() {
        let expr = parse("live_block()").unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "live_block"));
    }

    #[test]
    fn test_columns_with_named_args() {
        let expr = parse("columns(#{gap: 4, item_template: live_block()})").unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "columns");
            assert!(args.iter().any(|a| a.name.as_deref() == Some("gap")));
            assert!(
                args.iter()
                    .any(|a| a.name.as_deref() == Some("item_template"))
            );
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_col_reference() {
        let expr = parse("text(col(\"name\"))").unwrap();
        if let RenderExpr::FunctionCall { args, .. } = &expr {
            assert!(matches!(&args[0].value, RenderExpr::ColumnRef { name } if name == "name"));
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_nested_functions() {
        let expr =
            parse_render_dsl(r#"row(icon("folder"), spacer(6), text(col("name")))"#).unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "row");
            assert_eq!(args.len(), 3);
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_tree_with_col_refs() {
        let expr = parse(r#"tree(#{parent_id: col("parent_id"), sortkey: col("id"), item_template: render_entity()})"#).unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "tree");
            let parent_arg = args
                .iter()
                .find(|a| a.name.as_deref() == Some("parent_id"))
                .unwrap();
            assert!(
                matches!(&parent_arg.value, RenderExpr::ColumnRef { name } if name == "parent_id")
            );
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn test_json_backwards_compat() {
        // Old JSON with operations field should still parse (serde ignores unknown
        // fields)
        let json = r#"{"FunctionCall":{"name":"table","args":[],"operations":[]}}"#;
        let expr = parse(json).unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));

        let json = r#"{"FunctionCall":{"name":"table","args":[]}}"#;
        let expr = parse(json).unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));
    }

    #[test]
    fn test_empty_defaults_to_table() {
        let expr = parse("").unwrap();
        assert!(matches!(expr, RenderExpr::FunctionCall { ref name, .. } if name == "table"));
    }

    #[test]
    fn test_widget_with_integer_arg() {
        let expr = parse("chain_ops(0)").unwrap();
        if let RenderExpr::FunctionCall { name, args, .. } = &expr {
            assert_eq!(name, "chain_ops");
            assert_eq!(args.len(), 1);
        } else {
            panic!("Expected FunctionCall");
        }
    }

    /// Phase 2 exit criteria: a brand-new widget name parses without enum,
    /// parser, or registry change. The frontend just needs to add a builder
    /// for it — the parse path is extension-free.
    #[test]
    fn new_widget_parses_without_explicit_registration() {
        // Use parse_render_dsl directly with no register_widget_names call —
        // the source-driven discovery path must handle this on its own.
        let expr = parse_render_dsl(
            r#"kanban(#{group_by: "task_state", item_template: render_entity()})"#,
        )
        .unwrap();
        match expr {
            RenderExpr::FunctionCall { name, args } => {
                assert_eq!(name, "kanban");
                assert!(args.iter().any(|a| a.name.as_deref() == Some("group_by")));
                assert!(
                    args.iter()
                        .any(|a| a.name.as_deref() == Some("item_template"))
                );
            }
            other => panic!("Expected FunctionCall(kanban), got {other:?}"),
        }
    }

    #[test]
    fn nested_new_widgets_parse_without_registration() {
        let expr = parse_render_dsl(
            r#"calendar(#{view: "month", item_template: holiday_badge(text(col("title")))})"#,
        )
        .unwrap();
        if let RenderExpr::FunctionCall { name, args } = &expr {
            assert_eq!(name, "calendar");
            // The nested holiday_badge widget should have parsed too.
            let item_template = args
                .iter()
                .find(|a| a.name.as_deref() == Some("item_template"))
                .expect("calendar has item_template");
            assert!(matches!(
                &item_template.value,
                RenderExpr::FunctionCall { name, .. } if name == "holiday_badge"
            ));
        } else {
            panic!("Expected FunctionCall");
        }
    }

    #[test]
    fn extract_function_names_skips_string_literals_and_comments() {
        let source = r#"row(text("foo(bar)"), icon("baz")) // not_a_widget(blah)"#;
        let names = extract_function_names(source);
        assert!(names.contains(&"row".to_string()));
        assert!(names.contains(&"text".to_string()));
        assert!(names.contains(&"icon".to_string()));
        assert!(
            !names.contains(&"foo".to_string()),
            "string-literal contents must not register"
        );
        assert!(
            !names.contains(&"bar".to_string()),
            "string-literal contents must not register"
        );
        assert!(
            !names.contains(&"not_a_widget".to_string()),
            "comment contents must not register"
        );
    }

    #[test]
    fn extract_function_names_skips_rhai_keywords() {
        // `if` and `let` would happen to look like fn calls if they appeared
        // before `(` in the source — make sure they never get registered.
        let names = extract_function_names("if (x > 0) { table() }");
        assert!(!names.contains(&"if".to_string()));
        assert!(names.contains(&"table".to_string()));
    }

    // ── Predicate Rhai constructors (FU-2) ─────────────────────────────────
    //
    // Each constructor's output `RenderExpr` is evaluated to a `Value`, then
    // round-tripped through serde_json into a `Predicate` — the same path
    // `parse_rules_arg` (render_interpreter.rs) takes for `rules: [...]`.

    fn parse_predicate(source: &str) -> crate::predicate::Predicate {
        let expr = parse(source).expect("parse predicate DSL");
        let val = crate::eval_to_value(&expr, &HashMap::<String, crate::Value>::new());
        let json = serde_json::to_value(&val).expect("Value → JSON");
        serde_json::from_value::<crate::predicate::Predicate>(json).expect("JSON → Predicate")
    }

    #[test]
    fn predicate_eq() {
        match parse_predicate(r#"eq("level", 0)"#) {
            crate::predicate::Predicate::Eq { field, value } => {
                assert_eq!(field, "level");
                assert_eq!(value, crate::Value::Integer(0));
            }
            other => panic!("expected Eq, got {other:?}"),
        }
    }

    #[test]
    fn predicate_ne_gt_lt_gte_lte() {
        // All five share a shape; spot-check each variant rather than
        // five copies of the same matching boilerplate.
        use crate::predicate::Predicate::*;
        assert!(matches!(
            parse_predicate(r#"ne("status", "done")"#),
            Ne { .. }
        ));
        assert!(matches!(parse_predicate(r#"gt("count", 3)"#), Gt { .. }));
        assert!(matches!(parse_predicate(r#"lt("count", 3)"#), Lt { .. }));
        assert!(matches!(parse_predicate(r#"gte("count", 3)"#), Gte { .. }));
        assert!(matches!(parse_predicate(r#"lte("count", 3)"#), Lte { .. }));
    }

    #[test]
    fn predicate_is_not_null() {
        use crate::predicate::Predicate::*;
        match parse_predicate(r#"is_not_null("task_state")"#) {
            IsNotNull(field) => assert_eq!(field, "task_state"),
            other => panic!("expected IsNotNull, got {other:?}"),
        }
    }

    #[test]
    fn predicate_var_via_quoted_verbose_form() {
        // `var` is a Rhai reserved keyword (the tokenizer rejects it
        // even inside map literals as an unquoted identifier), so we
        // don't register a constructor for it. Verify the quoted-key
        // verbose form `#{"var": "<field>"}` still round-trips into
        // `Predicate::Var`.
        use crate::predicate::Predicate::*;
        match parse_predicate(r#"#{"var": "is_focused"}"#) {
            Var(field) => assert_eq!(field, "is_focused"),
            other => panic!("expected Var, got {other:?}"),
        }
    }

    #[test]
    fn predicate_not() {
        use crate::predicate::Predicate::*;
        match parse_predicate(r#"not(eq("level", 0))"#) {
            Not(inner) => match *inner {
                Eq { field, .. } => assert_eq!(field, "level"),
                other => panic!("expected Not(Eq), got Not({other:?})"),
            },
            other => panic!("expected Not, got {other:?}"),
        }
    }

    #[test]
    fn predicate_and_or_variadic() {
        use crate::predicate::Predicate::*;
        match parse_predicate(r#"and(eq("level", 0), gt("depth", 0))"#) {
            And(children) => {
                assert_eq!(children.len(), 2);
                assert!(matches!(&children[0], Eq { .. }));
                assert!(matches!(&children[1], Gt { .. }));
            }
            other => panic!("expected And, got {other:?}"),
        }
        // Three-arity to confirm the additional overloads are wired.
        match parse_predicate(r#"or(eq("a", 1), eq("b", 2), eq("c", 3))"#) {
            Or(children) => assert_eq!(children.len(), 3),
            other => panic!("expected Or, got {other:?}"),
        }
    }

    #[test]
    fn predicate_always() {
        assert!(matches!(
            parse_predicate("always()"),
            crate::predicate::Predicate::Always
        ));
    }

    #[test]
    fn rules_arg_round_trip_through_full_tree_call() {
        // Mirror the path `parse_rules_arg` takes on a real `tree(rules: [...])`
        // call: parse the DSL, find the `rules:` arg, evaluate it as a Value,
        // and deserialize each item as a `RuleSpec`. Confirms the constructors
        // compose with the rest of the DSL.
        let expr = parse(
            r#"tree(#{
                parent_id: col("parent_id"),
                rules: [
                    #{
                        when: and(eq("level", 0), gt("depth", 0)),
                        override: #{role: "page_title", show_bullet: false}
                    },
                    #{when: always(), override: #{}}
                ]
            })"#,
        )
        .unwrap();

        let RenderExpr::FunctionCall { args, .. } = expr else {
            panic!("expected tree(...) FunctionCall");
        };
        let rules_arg = args
            .iter()
            .find(|a| a.name.as_deref() == Some("rules"))
            .expect("rules: arg present");
        let rules_value =
            crate::eval_to_value(&rules_arg.value, &HashMap::<String, crate::Value>::new());
        let crate::Value::Array(items) = rules_value else {
            panic!("rules: must evaluate to Array");
        };

        let specs: Vec<crate::render_types::RuleSpec> = items
            .iter()
            .map(|item| {
                let json = serde_json::to_value(item).expect("Value → JSON");
                serde_json::from_value(json).expect("JSON → RuleSpec")
            })
            .collect();

        assert_eq!(specs.len(), 2);

        use crate::predicate::Predicate::*;
        match &specs[0].when {
            And(children) => {
                assert!(matches!(&children[0], Eq { field, .. } if field == "level"));
                assert!(matches!(&children[1], Gt { field, .. } if field == "depth"));
            }
            other => panic!("expected And in first rule, got {other:?}"),
        }
        assert_eq!(
            specs[0].overrides.get("role").and_then(|v| v.as_string()),
            Some("page_title")
        );
        assert_eq!(
            specs[0].overrides.get("show_bullet"),
            Some(&crate::Value::Boolean(false))
        );

        assert!(matches!(specs[1].when, Always));
    }
}
