use serde::Deserialize;
use serde::Serialize;

/// Metadata about a widget builder, generated by `#[widget_builder]`.
///
/// Used for:
/// - Scratch-like builder UI (category, params, doc)
/// - `all_widget_metas()` to replace hardcoded `is_template_arg()`
/// - Frontend capability negotiation (`UiInfo.available_widgets`)
///
/// flutter_rust_bridge:ignore
#[derive(Debug, Clone)]
pub struct WidgetMeta {
    pub name: &'static str,
    pub category: WidgetCategory,
    pub params: &'static [StaticParam],
    pub doc: &'static str,
}

/// Categorizes widgets for the builder UI.
///
/// This is metadata only — it does NOT drive code generation.
/// The `#[widget_builder]` macro infers behavior from param types instead.
///
/// flutter_rust_bridge:non_opaque
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WidgetCategory {
    /// Displays a single value (text, badge, checkbox, icon, spacer)
    Leaf,
    /// Structural container (row, block, section, columns)
    Layout,
    /// Iterates over data rows (list, tree, table, outline)
    Collection,
    /// Renders data fields, possibly with children (source_block, state_toggle,
    /// pref_field)
    Element,
    /// Special purpose (live_block, live_query, error, empty)
    Special,
}

/// Static parameter descriptor for `WidgetMeta`.
///
/// Like `OperationParam` but with `&'static str` for use in const contexts.
///
/// flutter_rust_bridge:ignore
#[derive(Debug, Clone)]
pub struct StaticParam {
    pub name: &'static str,
    pub type_hint: &'static str,
    pub default: Option<&'static str>,
}

impl WidgetMeta {
    /// How this widget classifies the named arg, or `None` when it declares no
    /// param under that name. `Some(true)` = the arg must stay an unevaluated
    /// template; `Some(false)` = it is a scalar to evaluate against the row.
    ///
    /// Templateness is a PER-WIDGET property: `header` is a template for
    /// `expand_toggle` and could be a plain string elsewhere. Widgets that
    /// declare no params at all (`raw fn`) answer `None` and leave the caller
    /// on the global `is_template_arg` allowlist.
    pub fn classifies_as_template(&self, name: &str) -> Option<bool> {
        self.params
            .iter()
            .find(|p| p.name == name)
            .map(|p| p.type_hint == "Expr" || p.type_hint == "Collection")
    }
}
