use serde::{Deserialize, Serialize};

/// Metadata about a widget builder, generated by `#[widget_builder]`.
///
/// Used for:
/// - Scratch-like builder UI (category, params, doc)
/// - `all_widget_metas()` to replace hardcoded `is_template_arg()`
/// - Frontend capability negotiation (`UiInfo.available_widgets`)
///
/// flutter_rust_bridge:ignore
#[derive(Debug, Clone)]
pub struct WidgetMeta {
    pub name: &'static str,
    pub category: WidgetCategory,
    pub params: &'static [StaticParam],
    pub doc: &'static str,
}

/// Categorizes widgets for the builder UI.
///
/// This is metadata only — it does NOT drive code generation.
/// The `#[widget_builder]` macro infers behavior from param types instead.
///
/// flutter_rust_bridge:non_opaque
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WidgetCategory {
    /// Displays a single value (text, badge, checkbox, icon, spacer)
    Leaf,
    /// Structural container (row, block, section, columns)
    Layout,
    /// Iterates over data rows (list, tree, table, outline)
    Collection,
    /// Renders data fields, possibly with children (source_block, state_toggle, pref_field)
    Element,
    /// Special purpose (block_ref, live_query, error, empty)
    Special,
}

/// Static parameter descriptor for `WidgetMeta`.
///
/// Like `OperationParam` but with `&'static str` for use in const contexts.
///
/// flutter_rust_bridge:ignore
#[derive(Debug, Clone)]
pub struct StaticParam {
    pub name: &'static str,
    pub type_hint: &'static str,
    pub default: Option<&'static str>,
}

/// Check whether `name` is a template/expression arg according to widget metas.
///
/// Replaces the hardcoded `is_template_arg()` in render_eval.rs.
///
/// flutter_rust_bridge:ignore
pub fn is_template_arg_from_metas(metas: &[&WidgetMeta], name: &str) -> bool {
    for meta in metas {
        for param in meta.params {
            if param.name == name && (param.type_hint == "Expr" || param.type_hint == "Collection")
            {
                return true;
            }
        }
    }
    false
}
