// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import '../third_party/holon_api.dart';
import '../third_party/holon_api/auth.dart';
import '../third_party/holon_api/render_types.dart';
import '../third_party/holon_api/streaming.dart';
import '../third_party/holon_api/types.dart';
import '../third_party/holon_api/widget_spec.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `clear_pbt_engine`, `create_span_from_context`, `default_env_filter`, `get_session`, `init_opentelemetry`, `set_pbt_engine`, `spawn_stream_forwarder`

/// The root layout block ID (EntityUri string, e.g. "block:root-layout").
/// Single source of truth — Flutter should use this instead of hardcoding.
Future<String> rootLayoutBlockId() =>
    RustLib.instance.api.crateApiFfiBridgeRootLayoutBlockId();

/// Initialize the render engine with a database at the given path
///
/// This is the main entry point for Flutter. It creates a `FrontendSession` which:
/// 1. Initializes the database and schema (including materialized views)
/// 2. Waits for file watcher readiness (if OrgMode is configured)
/// 3. Detects any startup errors
///
/// The session is stored globally so that subsequent FFI calls can access it.
/// All query methods go through `FrontendSession`, ensuring they can only be
/// called after initialization completes.
///
/// # Parameters
/// * `db_path` - Path to the database file
/// * `config` - Configuration map containing:
///   - `TODOIST_API_KEY` - Todoist API key for sync
///   - `ORGMODE_ROOT_DIRECTORY` - OrgMode files root directory
///   - `MCP_SERVER_PORT` - Port for MCP HTTP server (optional, starts server if provided)
///
/// # Returns
/// An opaque handle to the session. The actual `FrontendSession` is stored globally
/// and accessed by subsequent FFI calls. This return value is kept alive by Flutter
/// to prevent the Rust Bridge from disposing the underlying resources.
Future<ArcFrontendSession> initRenderEngine({
  required String dbPath,
  required Map<String, String> config,
}) => RustLib.instance.api.crateApiFfiBridgeInitRenderEngine(
  dbPath: dbPath,
  config: config,
);

/// Watch a block's UI with automatic error recovery and structural hot-swap.
///
/// Returns a `FfiWatchHandle` for variant switching. UiEvents (Structure + Data)
/// are sent to the provided sink. Unlike `render_block`, errors become
/// `UiEvent::Structure` events with inline error WidgetSpecs — the stream
/// stays open and recovers when the block is fixed.
Future<FfiWatchHandle> watchUi({
  required String blockId,
  required UiEventSink sink,
  String? preferredVariant,
  required bool isRoot,
}) => RustLib.instance.api.crateApiFfiBridgeWatchUi(
  blockId: blockId,
  sink: sink,
  preferredVariant: preferredVariant,
  isRoot: isRoot,
);

/// Switch the entity profile variant for an active watch_ui stream.
Future<void> setVariant({
  required FfiWatchHandle handle,
  required String variant,
}) => RustLib.instance.api.crateApiFfiBridgeSetVariant(
  handle: handle,
  variant: variant,
);

/// Compile a PRQL query, execute it, and set up CDC streaming
///
/// This combines query compilation, execution, and change watching into a single call.
/// Returns a WidgetSpec (render spec + data) and forwards CDC events to the sink.
///
/// # Returns
/// - `WidgetSpec`: Contains render_spec and data (actions empty for regular queries)
///
/// # UI Usage
/// The UI should:
/// 1. Subscribe to the MapChangeSink using StreamBuilder in Flutter
/// 2. Key widgets by entity ID from data.get("id"), NOT by rowid
/// 3. Handle Added/Updated/Removed events to update UI
///
Future<WidgetSpec> queryAndWatch({
  required String prql,
  required Map<String, Value> params,
  required MapChangeSink sink,
  TraceContext? traceContext,
  String? contextBlockId,
  String? language,
  String? preferredVariant,
}) => RustLib.instance.api.crateApiFfiBridgeQueryAndWatch(
  prql: prql,
  params: params,
  sink: sink,
  traceContext: traceContext,
  contextBlockId: contextBlockId,
  language: language,
  preferredVariant: preferredVariant,
);

/// Render a block by its ID.
///
/// Given a block ID, finds its query source child, compiles and executes the query,
/// parses any render sibling into a RenderExpr, and returns a WidgetSpec + CDC stream.
///
/// For the root block, pass `is_root: true` to include global actions.
Future<WidgetSpec> renderBlock({
  required String blockId,
  required MapChangeSink sink,
  String? preferredVariant,
  required bool isRoot,
}) => RustLib.instance.api.crateApiFfiBridgeRenderBlock(
  blockId: blockId,
  sink: sink,
  preferredVariant: preferredVariant,
  isRoot: isRoot,
);

/// Get available operations for an entity
///
/// Returns a list of operation descriptors available for the given entity_name.
/// Use "*" as entity_name to get wildcard operations.
///
/// # FFI Function
/// This is exposed to Flutter via flutter_rust_bridge
Future<List<OperationDescriptor>> availableOperations({
  required String entityName,
}) => RustLib.instance.api.crateApiFfiBridgeAvailableOperations(
  entityName: entityName,
);

/// Execute an operation on the database
///
/// # FFI Function
/// This is exposed to Flutter via flutter_rust_bridge
///
/// Operations mutate the database directly. UI updates happen via CDC streams.
/// This follows the unidirectional data flow: Action → Model → View
///
/// # Note
/// This function does NOT return new data. Changes propagate through:
/// Operation → DB mutation → CDC event → watch_query stream → UI update
Future<String?> executeOperation({
  required String entityName,
  required String opName,
  required Map<String, Value> params,
  TraceContext? traceContext,
}) => RustLib.instance.api.crateApiFfiBridgeExecuteOperation(
  entityName: entityName,
  opName: opName,
  params: params,
  traceContext: traceContext,
);

/// Look up a render sibling block for a given parent block ID.
///
/// Previously found a block with `source_language = "render"` that shares the same parent_id.
/// TODO: Render sibling lookup was removed with PRQL render directive removal.
/// This stub remains for FFI compatibility.
Future<String?> lookupRenderSibling({required String parentId}) => RustLib
    .instance
    .api
    .crateApiFfiBridgeLookupRenderSibling(parentId: parentId);

/// Check if an operation is available for an entity
///
/// # FFI Function
/// This is exposed to Flutter via flutter_rust_bridge
///
/// # Returns
/// `true` if the operation is available, `false` otherwise
Future<bool> hasOperation({
  required String entityName,
  required String opName,
}) => RustLib.instance.api.crateApiFfiBridgeHasOperation(
  entityName: entityName,
  opName: opName,
);

/// Undo the last operation
///
/// Executes the inverse operation from the undo stack and pushes it to the redo stack.
/// Returns true if an operation was undone, false if the undo stack is empty.
Future<bool> undo() => RustLib.instance.api.crateApiFfiBridgeUndo();

/// Redo the last undone operation
///
/// Executes the inverse of the last undone operation and pushes it back to the undo stack.
/// Returns true if an operation was redone, false if the redo stack is empty.
Future<bool> redo() => RustLib.instance.api.crateApiFfiBridgeRedo();

/// Check if undo is available
Future<bool> canUndo() => RustLib.instance.api.crateApiFfiBridgeCanUndo();

/// Check if redo is available
Future<bool> canRedo() => RustLib.instance.api.crateApiFfiBridgeCanRedo();

/// Get the initial widget for the application root
///
/// Get authentication status for all configured MCP providers.
///
/// Returns a list of `ProviderAuthStatus` indicating whether each provider
/// is authenticated, needs OAuth consent, or has a failed auth state.
/// Frontends should poll this after initialization and display appropriate UI.
Future<List<ProviderAuthStatus>> getProviderAuthStatuses() =>
    RustLib.instance.api.crateApiFfiBridgeGetProviderAuthStatuses();

/// Complete an OAuth consent flow after the user authorized in the browser.
///
/// The frontend captures the OAuth redirect callback URL (via flutter_web_auth_2)
/// and extracts the `code` and `state` query parameters, then passes them here.
/// Rust exchanges the code for a token and connects to the MCP server.
///
/// # Parameters
/// * `provider_name` - The provider identifier (MCP server URI) from `NeedsConsent`
/// * `code` - The authorization code from the OAuth callback `?code=...`
/// * `state` - The CSRF state from the OAuth callback `?state=...`
Future<void> completeProviderOauth({
  required String providerName,
  required String code,
  required String state,
}) => RustLib.instance.api.crateApiFfiBridgeCompleteProviderOauth(
  providerName: providerName,
  code: code,
  state: state,
);

/// Interpret a WidgetSpec into a ViewModel tree and return it as JSON.
///
/// This is the same interpretation that GPUI does inline (shadow_interp.interpret).
/// Flutter calls this after receiving a UiEvent::Structure to get the pre-built
/// widget tree, avoiding the need for Dart-side RenderInterpreter.
///
/// The returned JSON follows the serde serialization of `ViewModel` with
/// `NodeKind` tagged as `{"widget": "text", "content": "...", ...}`.
Future<String> interpretWidgetSpec({required WidgetSpec widgetSpec}) => RustLib
    .instance
    .api
    .crateApiFfiBridgeInterpretWidgetSpec(widgetSpec: widgetSpec);

/// Interpret a RenderExpr with data rows into a ViewModel JSON string.
///
/// Like `interpret_widget_spec` but takes a bare RenderExpr + rows instead of
/// a full WidgetSpec. Used by settings screen and other non-watch_ui paths.
Future<String> interpretRenderExpr({
  required RenderExpr renderExpr,
  required List<Map<String, Value>> rows,
}) => RustLib.instance.api.crateApiFfiBridgeInterpretRenderExpr(
  renderExpr: renderExpr,
  rows: rows,
);

/// Evaluate a RenderExpr to a Value given a row of data.
///
/// This is the same evaluation logic used by all Rust frontends.
/// Flutter calls this instead of reimplementing evaluation in Dart.
Future<Value> evalRenderExpr({
  required RenderExpr expr,
  required Map<String, Value> row,
}) =>
    RustLib.instance.api.crateApiFfiBridgeEvalRenderExpr(expr: expr, row: row);

/// Evaluate a binary operation on two Values.
Future<Value> evalBinary({
  required BinaryOperator op,
  required Value left,
  required Value right,
}) => RustLib.instance.api.crateApiFfiBridgeEvalBinary(
  op: op,
  left: left,
  right: right,
);

/// Convert a Value to its display string representation.
Future<String> valueDisplayString({required Value value}) =>
    RustLib.instance.api.crateApiFfiBridgeValueDisplayString(value: value);

/// Check if a widget is open (default: true if not stored).
Future<bool> isWidgetOpen({required String blockId}) =>
    RustLib.instance.api.crateApiFfiBridgeIsWidgetOpen(blockId: blockId);

/// Set a widget's open/close state and persist to disk.
Future<void> setWidgetOpen({required String blockId, required bool open}) =>
    RustLib.instance.api.crateApiFfiBridgeSetWidgetOpen(
      blockId: blockId,
      open: open,
    );

/// Get the preferences UI render data.
///
/// Returns a RenderExpr tree and data rows describing all preference fields.
/// Flutter renders this with its existing RenderInterpreter / BuilderRegistry.
Future<PreferencesRenderData> getPreferencesRender() =>
    RustLib.instance.api.crateApiFfiBridgeGetPreferencesRender();

/// Read a preference value by key.
///
/// Returns the current value as a JSON string (or default if not set).
/// Keys use dotted notation, e.g. "ui.theme", "todoist.api_key".
Future<String> getPreference({required String key}) =>
    RustLib.instance.api.crateApiFfiBridgeGetPreference(key: key);

/// Set a preference value by key and persist to disk.
///
/// The value is a plain string — Rust parses it into the appropriate type
/// based on the preference definition. Keys use dotted notation.
Future<void> setPreference({required String key, required String value}) =>
    RustLib.instance.api.crateApiFfiBridgeSetPreference(key: key, value: value);

/// Set a boolean preference value by key and persist to disk.
Future<void> setPreferenceBool({required String key, required bool value}) =>
    RustLib.instance.api.crateApiFfiBridgeSetPreferenceBool(
      key: key,
      value: value,
    );

/// Install the PBT's BackendEngine as GLOBAL_SESSION.
///
/// Called during `pbt_setup` after StartApp completes. Wraps the PBT engine
/// in a FrontendSession and sets it as GLOBAL_SESSION. When Flutter's
/// `init_render_engine` is subsequently called, it detects the existing
/// session (hot restart path) and reuses it — so the Flutter app and PBT
/// share the same database.
Future<void> installPbtAsGlobalSession() =>
    RustLib.instance.api.crateApiFfiBridgeInstallPbtAsGlobalSession();

/// Execute an operation on the PBT's BackendEngine.
///
/// Called by the Dart callback during `run_shared_pbt`. Routes mutations to the
/// PBT's own engine (separate from the production GLOBAL_SESSION), ensuring the
/// PBT's TestEnvironment sees the mutations.
Future<void> pbtExecuteOperation({
  required String entityName,
  required String opName,
  required Map<String, Value> params,
}) => RustLib.instance.api.crateApiFfiBridgePbtExecuteOperation(
  entityName: entityName,
  opName: opName,
  params: params,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ArcFrontendSession>>
abstract class ArcFrontendSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FfiWatchHandle>>
abstract class FfiWatchHandle implements RustOpaqueInterface {}

/// flutter_rust_bridge:non_opaque
class MapChangeSink {
  final RustStreamSink<BatchMapChangeWithMetadata> sink;

  const MapChangeSink({required this.sink});

  @override
  int get hashCode => sink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MapChangeSink &&
          runtimeType == other.runtimeType &&
          sink == other.sink;
}

/// Preference render data returned to Flutter.
///
/// Contains the RenderExpr tree (section > pref_field) and data rows
/// with current values. Flutter renders this with its RenderInterpreter.
///
/// flutter_rust_bridge:non_opaque
class PreferencesRenderData {
  final RenderExpr renderExpr;
  final List<Map<String, Value>> rows;

  const PreferencesRenderData({required this.renderExpr, required this.rows});

  @override
  int get hashCode => renderExpr.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreferencesRenderData &&
          runtimeType == other.runtimeType &&
          renderExpr == other.renderExpr &&
          rows == other.rows;
}

/// Sink for UiEvent stream (required by FRB — can't use type alias for StreamSink<T>)
///
/// flutter_rust_bridge:non_opaque
class UiEventSink {
  final RustStreamSink<UiEvent> sink;

  const UiEventSink({required this.sink});

  @override
  int get hashCode => sink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UiEventSink &&
          runtimeType == other.runtimeType &&
          sink == other.sink;
}
