// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_transition`

/// Run the full PBT state machine with Flutter providing UI mutations via callback.
Future<String> runSharedPbt({
  required FutureOr<void> Function(String, String, String) applyMutationCb,
  required int numSteps,
}) => RustLib.instance.api.crateApiSharedPbtRunSharedPbt(
  applyMutationCb: applyMutationCb,
  numSteps: numSteps,
);

/// Flutter-specific pbt_setup that also installs the PBT engine as GLOBAL_SESSION.
Future<String> pbtSetup({required int numSteps}) =>
    RustLib.instance.api.crateApiSharedPbtPbtSetup(numSteps: numSteps);

/// Flutter-specific pbt_teardown that also clears the PBT engine.
Future<String> pbtTeardown() =>
    RustLib.instance.api.crateApiSharedPbtPbtTeardown();
